"""
Emit the ``processes/landscape_*`` directories for the S1b benchmarks.

The other AIDA-Scout signals are written by ``make_signal_cards.py`` at the
repository root, but the landscape points are not a card-writing task: their
hard process is the Python cascade generator in this package, and the card only
tells Pythia where to find the LHE it produces.  This script is the landscape
equivalent -- edit it, not the generated files.

    python3 -m landscape.make_processes            # writes into processes/

Each point gets three files:

  <name>_pythia_card.dat   Pythia settings, with _LHEFILE_ / NEVENTS / NSEED
                           placeholders that run.sh substitutes
  <name>_lhe_args.dat      one line of arguments for landscape.make_lhe; its
                           presence is what makes run.sh do the LHE pre-step
  README.md                parameters, lifetimes, and which seeds it should fail

The spectrum seed is deliberately NOT in the args file as a run-time knob: it
is part of the benchmark definition in params.BENCHMARKS, so every parallel job
of a point shares one landscape realisation.  L-D varies the realisation by
being three separate benchmarks.
"""

import argparse
import os

# The generator-level jet filter and the decision of which points carry it live
# in make_signal_cards.py, at the repository root, so that every signal in the
# campaign is classified in exactly one place.  Run this module from the
# repository root (python3 -m landscape.make_processes) so the import resolves.
from make_signal_cards import jet_filter_block

from .params import (SMConstants, BENCHMARKS, benchmark_entry,
                     LAMBDA_RETUNED, LD_SPECTRUM_SEEDS)
from .generate import draw_spectrum
from . import lhe as LHE
from . import lifetimes as LT
from . import production as P
from . import retune as RT


#: benchmark tag -> process directory name
PROCESS_NAMES = {
    "L-A": "landscape_LA_direct",
    "L-B": "landscape_LB_higgs",
    "L-B-displaced": "landscape_LB_higgs_displaced",
    "L-C": "landscape_LC_control",
    "L-D1": "landscape_LD_spectrum1",
    "L-D2": "landscape_LD_spectrum2",
    "L-D3": "landscape_LD_spectrum3",
}


CARD = """! ---------------------------------------------------------------------------
! AIDA-Scout S1b -- landscape scalar cascades, benchmark {tag}
!
! {oneline}
!
! The hard process is NOT a Pythia process.  landscape.make_lhe writes an LHE
! file containing the fully decayed hidden-sector cascade -- N = 200 singlet
! scalars sharing one PDG id, each carrying its own mass and its own proper
! decay length -- and Pythia reads it with Beams:frameType = 4, showering and
! hadronising the Standard Model partons at the ends of the chains.
!
! Generated by landscape/make_processes.py -- edit that script, not this file.
! ---------------------------------------------------------------------------

Random:setSeed = on
Random:seed = NSEED
Main:numberOfEvents = NEVENTS

! The only generator-level cut is the jet filter at the bottom of this card,
! which reproduces the parton-level jet requirement the MadGraph Standard Model
! samples carry.  No pT / eta / mass cut is applied to the signal objects
! themselves: these signals live entirely below the thresholds that a default
! cut set would impose (spec section 4).

Init:showChangedSettings = on
Init:showChangedParticleData = on
Next:numberCount = 500
Next:numberShowInfo = 0
Next:numberShowProcess = 1
Next:numberShowEvent = 0

! ---- Hard process: the LHE written by landscape.make_lhe -------------------
! run.sh substitutes _LHEFILE_ with the path it generated for this job.
Beams:LHEF = _LHEFILE_

{fragment}
"""


def one_line(tag):
    model, mode, seed = benchmark_entry(tag)
    if mode == "direct":
        return ("direct gluon-fusion production of a single hidden scalar "
                "through its Higgs admixture; shipped driver parameters")
    if tag == "L-C":
        return ("negative control: lambda'/lambda = 1e-6, so the scalars decay "
                "straight to the SM and the cascade never starts")
    if tag == "L-B-displaced":
        return ("h -> phi_i phi_j at the shipped lambda = 1e-4; same topology "
                "as L-B but 730x longer-lived scalars")
    if tag.startswith("L-D"):
        return ("h -> phi_i phi_j, as L-B on an independent landscape "
                "realisation (spectrum seed {0})".format(seed))
    return ("h -> phi_i phi_j with lambda retuned to the Higgs "
            "signal-strength bound; the headline point")


def card(tag):
    return CARD.format(tag=tag, oneline=one_line(tag),
                       fragment=LHE.pythia_fragment())


def lhe_args(tag):
    return ("# arguments for landscape.make_lhe; run.sh appends --nevents,\n"
            "# --seed and --out.  One line, comments ignored.\n"
            "--benchmark {0} --fast-branching\n".format(tag))


# ---------------------------------------------------------------------------
# READMEs
# ---------------------------------------------------------------------------

MENU = """
| Seed | Threshold | Fires? |
|---|---|---|
| PuppiHT | 450 (constituents pT > 30) | {ht} |
| SinglePuppiJet | 230 | {jet} |
| QuadJet | 400,70,55,40,40 | {quad} |
| DoubleTkMuon (BPH) | 2,2, abs(eta)<1.5, dR<1.4, OS, dz<1cm | {bph} |
| DoubleTkMuon (central) | 4,4 | {mu44} |
| DoubleTkElectron | 25,12 | {ele} |
| DoubleTkIsoPhoton | 22,12 | {pho} |
| DoublePuppiTau | 52,52 | {tau} |
| PuppiETmiss | 200 | {met} |
"""

README = """# {name}

**AIDA-Scout S1b (landscape scalar cascades), benchmark `{tag}`** -- generated by
`landscape/make_processes.py`.

{what}

Reference: R. T. D'Agnolo, M. Ettengruber, L.-T. Wang, *Landscapes at
Colliders*, arXiv:2512.18001. The model is a Python port of the authors' Julia
code; see [`landscape/README.md`](../../landscape/README.md) for the port, its
eight-tier verification, and the deliberate deviations.

## Parameters

| | |
|---|---|
| N (number of singlet scalars) | {N} |
| lambda | {lam:g} |
| lambda' | {lamp:g} |
| lambda'/lambda | {ratio:.3g} |
| M* | {mstar:g} GeV |
| v2 | {vev2:g} GeV |
| mixing angle theta | {theta:.4g} |
| mass spectrum | uniform on [{mlow:.4f}, {mhigh:g}] GeV |
| **spectrum seed** | **{seed}** (one landscape realisation, fixed across jobs) |
| production | {mode} |

## Normalisation

| | |
|---|---|
| cross section x BR | **{xsec:.4g} pb** |
| BR(h -> BSM), physical (Gamma_SM = 4.1e-3 GeV) | {br_phys:.4g} |
| BR(h -> BSM), Julia normalisation (Gamma_bb(pole) x 1.89) | {br_code:.4g} |
| Higgs signal-strength bound | 0.1 -- **{verdict}** |

{norm_note}

## Lifetimes

```
{lifetimes}
```

{life_note}

## Why it evades (or does not evade) the Phase-2 L1 menu
{menu}
{notes}
## Running

```bash
apptainer exec --bind $simdir \\
  /cvmfs/unpacked.cern.ch/registry.hub.docker.com/jmduarte/mapyde:latest \\
  sh $simdir/run.sh {name} <nevents> <seed> $simdir False
```

This point uses the **pythia** branch of `run.sh`, with the landscape LHE
pre-step in front of it. `run.sh` runs `landscape.make_lhe` with the arguments
in `{name}_lhe_args.dat`, writes the parton-level summary to
`outdir/parton_level.txt`, and then hands the LHE to the same Pythia -> HepMC
-> PU 200 -> Delphes -> parquet chain every other point uses.

To produce the LHE on its own, outside the job:

```bash
python3 -m landscape.make_lhe --benchmark {tag} --fast-branching \\
    --nevents 10000 --seed 1234 --out {tag}.lhe --fragment {tag}.cmnd
```
"""


BMESON_NOTE = """**The cross section is dominated by a dimensionally inconsistent term in the
original code, and should not be used as a rate without reading this.** The
Julia's production sum adds `1e-3 * bmesondecay` -- a dimensionless
branching-ratio-like quantity -- to two terms that are cross sections in barns
(`ScalarProductionshare.jl` lines 66-81 and 143-153). It contributes
{bmeson:.4g} pb against {direct:.4g} pb of genuine direct production, a factor
{ratio:.0f}. Because it is nonzero only below 4.7 GeV it also skews *which*
scalar is produced, not just the normalisation. It is reproduced as written,
because it is what defines the authors' L-A; pass `--no-bmeson-term` to
`landscape.make_lhe` to drop it, which gives {without:.4g} pb.
"""

RETUNE_NOTE = """lambda is retuned from the shipped 1e-4 to {lam:g}, which is what puts this
point at the Higgs signal-strength bound instead of three orders of magnitude
below it. Gamma(h -> phi phi) goes as lambda^2 and nothing else in the chain
depends on lambda, so the retuning is a closed form -- `landscape/retune.py`.

The bound is applied to the **physical** BR. The Julia normalises to
Gamma_bb(pole) x 1.89 = 8.13e-3 GeV against a true SM width of 4.1e-3, so
tuning its number to 0.1 would land at a physical 0.17, over the bound
(deviation 7d).

lambda' is deliberately **not** scaled with lambda. Every hidden-sector width
carries lambda'^2 and every Standard Model width carries theta^2 ~ lambda^2, so
raising lambda alone reweights hidden against SM -- but the hidden channels
already hold at least 1 - 6.9e-8 of every above-threshold scalar's width at the
shipped point, and a factor 729 in lambda^2 leaves them at 1 - 5.0e-5. The
largest change in hidden fraction anywhere in the spectrum is 5.0e-5, and 400
cascades driven by the same uniform stream come out element-for-element
identical, so multiplicity and flavour composition are unchanged.
`landscape/tests/test_tier8_retune.py` asserts both.
"""

SHIPPED_NOTE = """lambda is the **shipped** 1e-4, not the retuned {retuned:g} that `L-B` uses.
The rate is 730x lower, but that is not why this point exists: below the
hidden-pair threshold a scalar has no hidden channel open, so its width is pure
mixing and ctau goes as lambda^-2. At the shipped lambda those scalars live
730x longer, and the sample is **displaced** where L-B is prompt. It is a
different signature, not a weaker L-B.
"""

DISPLACED_LIFE = """Every cascade *terminates* on a sub-threshold scalar, so this displacement is
not a tail -- it is where essentially all the visible partons come from.
"""

PROMPT_LIFE = """The sub-threshold scalars still carry the longest lifetimes, but at this lambda
they are microns, so the sample is prompt for all detector purposes. `L-B-displaced`
is the same topology with the shipped lambda, where the same scalars reach
millimetres.
"""

DOWNSTREAM = """
## Downstream limits

* `cards/delphes_card.dat` has **no d0 dependence** in its L1T tracking
  efficiencies -- they are functions of pt and eta only. The sample is correct
  at truth level, but the chain will not reproduce the loss of displaced tracks
  at L1. This matters most for `landscape_LB_higgs_displaced` and
  `landscape_LA_direct`.
* Delphes drops particles produced outside the tracker (R = 1.29 m, half-length
  3 m).
* **L1 menu decision bits are not produced here.** No CMSSW Phase-2 emulator
  exists in this repository; the menu column above is truth-level Pythia against
  the offline thresholds, which is an upper bound on what the real menu sees.
"""

LHE_NOTE = """
## What is in the LHE

The hidden scalars are written into the record, not just the final partons.
They share one PDG id (9000006) and each carries its own mass and its own
`VTIMUP`, because an LHE has nowhere else to put a per-particle displacement
and the cascade's decay vertices are the physics.

`LesHouches:setLifetime = 1` in the card is load-bearing: it is Pythia's
default, but `= 2` silently discards `VTIMUP` and collapses every hidden-scalar
decay vertex to the origin, making the sample prompt with no error. Verified by
A/B: with `= 1` the scalar decay vertices reach 232 mm; with `= 2` they are all
exactly zero.

Colour is connected **locally**: each phi -> q qbar is its own singlet with one
fresh tag, each phi -> g g its own closed loop with two. Connecting colour
across the cascade would string the whole event together and materially change
the hadronic activity.
"""


def readme(tag, name, measured=None):
    model, mode, seed = benchmark_entry(tag)
    consts = SMConstants()
    spectrum = draw_spectrum(model, seed)
    measured = measured or {}

    if mode == "direct":
        xs, _ = P.cross_sections(spectrum, consts, model)
        xsec = sum(xs) * 1e12
        h, d, b = P.production_breakdown(spectrum, consts, model,
                                         P.SIGMA_H_CROSSSECTIONS)
        norm_note = BMESON_NOTE.format(
            bmeson=b * 1e12, direct=d * 1e12,
            ratio=(b / d) if d else float("nan"),
            without=(h + d) * 1e12)
    else:
        xs, _ = P.cross_sections_higgs_only(spectrum, consts, model)
        xsec = sum(xs) * 1e12
        if model.lam == LAMBDA_RETUNED:
            norm_note = RETUNE_NOTE.format(lam=model.lam)
        else:
            norm_note = SHIPPED_NOTE.format(retuned=LAMBDA_RETUNED)

    br_phys = RT.br_h_to_bsm_physical(spectrum, consts, model)
    life = LT.summarise(spectrum, consts, model)
    life_note = (DISPLACED_LIFE if life["below_median_mm"] > 0.1
                 else PROMPT_LIFE)

    notes = LHE_NOTE + measured.get("notes", "") + DOWNSTREAM

    return README.format(
        name=name, tag=tag, what=measured.get("what", one_line(tag)),
        N=model.N, lam=model.lam, lamp=model.lam_prime,
        ratio=model.lam_prime / model.lam,
        mstar=model.M_star, vev2=model.vev_2, theta=model.mixing(consts),
        mlow=model.mass_low, mhigh=model.mass_high, seed=seed,
        mode=("direct ggF (+ the Julia's B-meson term)" if mode == "direct"
              else "gg -> h -> phi_i phi_j"),
        xsec=xsec, br_phys=br_phys,
        br_code=P.br_h_to_bsm(spectrum, consts, model),
        verdict=("within" if br_phys <= RT.BR_BOUND * (1 + 1e-9)
                 else "VIOLATED"),
        norm_note=norm_note,
        lifetimes=LT.format_summary(spectrum, consts, model, label=tag),
        life_note=life_note,
        menu=MENU.format(**measured.get("menu", DEFAULT_MENU)),
        notes=notes)


# Until a point has been measured, say so rather than guessing.
DEFAULT_MENU = {k: "to measure" for k in
                ("ht", "jet", "quad", "bph", "mu44", "ele", "pho", "tau",
                 "met")}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--outdir", default="processes")
    ap.add_argument("--only", default=None,
                    help="write just this benchmark tag")
    args = ap.parse_args(argv)

    from . import measured as MEAS

    written = []
    for tag in sorted(BENCHMARKS):
        if args.only and tag != args.only:
            continue
        name = PROCESS_NAMES[tag]
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "{0}_pythia_card.dat".format(name)), "w") as fh:
            fh.write(card(tag) + jet_filter_block(name))
        with open(os.path.join(d, "{0}_lhe_args.dat".format(name)), "w") as fh:
            fh.write(lhe_args(tag))
        with open(os.path.join(d, "README.md"), "w") as fh:
            fh.write(readme(tag, name, MEAS.MEASURED.get(tag)))
        written.append(d)

    for d in written:
        print("wrote " + d)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
