#!/usr/bin/env python3
"""
make_signal_cards.py

Generates the AIDA-Scout signal and control process directories under
processes/.  Everything it writes is a plain card of the kind the repo already
uses, so the generated points are ordinary processes as far as run.sh,
write_jobs.py and submit_to_condor.py are concerned.  The script exists so the
parameter scans stay reproducible: re-running it regenerates every point.

    python3 make_signal_cards.py [--outdir processes]

Two card flavours are produced:

  *_pythia_card.dat   Pythia8-only generation (Hidden Valley dark showers,
                      Higgs portal, Z').  Consumed by main_signal.cc via the
                      'pythia' branch of run.sh.  NEVENTS / NSEED are
                      placeholders, matching processes/minbias.

  *_proc_card.dat + *_run_card.dat + *_param_card.dat
                      MadGraph hard process (RPV MSSM), consumed by the
                      existing 'madgraph' branch of run.sh.

See processes/README_AIDA_Scout.md for the physics rationale per point.
"""

import argparse
import os

# ---------------------------------------------------------------------------
# Shared header.  Beam energy and tune come from main_signal.cc; anything set
# here overrides those defaults.
# ---------------------------------------------------------------------------

HEADER = """! ---------------------------------------------------------------------------
! {title}
!
! {subtitle}
!
! Generated by make_signal_cards.py -- edit that script, not this file.
! ---------------------------------------------------------------------------

Beams:idA = 2212
Beams:idB = 2212
Beams:eCM = 14000.

Random:setSeed = on
Random:seed = NSEED
Main:numberOfEvents = NEVENTS

! No generator-level cuts of any kind are applied: these signals live entirely
! below the thresholds that a default cut set would impose (spec section 4).

Init:showChangedSettings = on
Init:showChangedParticleData = on
Next:numberCount = 500
Next:numberShowInfo = 0
Next:numberShowProcess = 1
Next:numberShowEvent = 0
"""


def hv_block(lam, ngauge=3, nflav=2, prob_vector=0.75, alpha_fsr=None):
    """
    Hidden Valley shower + hadronisation settings (spec section S2).

    alpha_fsr = None reproduces the specification fragment exactly: running
    coupling (alphaOrder = 1) with the shower cutoff tied to Lambda.

    alpha_fsr = <value> switches to a fixed, strong hidden-sector coupling and
    decouples the cutoff from Lambda.  This is the high-multiplicity
    configuration: with alphaOrder = 1 the cutoff pTminFSR = 1.1 x Lambda sits
    exactly where the running coupling becomes large, so almost no hidden-sector
    radiation is generated and the dark meson multiplicity is insensitive to
    Lambda (measured: 4.0 -> 5.8 mesons/event across Lambda = 0.5 - 2 GeV).
    Fixing alphaFSR near 1 and dropping the cutoff to 0.5 GeV raises it to
    ~17 mesons and softens the leptons correspondingly.
    """
    if alpha_fsr is None:
        alpha_lines = """HiddenValley:alphaOrder = 1
HiddenValley:Lambda     = {lam:g}
HiddenValley:pTminFSR   = {ptmin:g}""".format(lam=lam, ptmin=1.1 * lam)
    else:
        alpha_lines = """HiddenValley:alphaOrder = 0
HiddenValley:alphaFSR   = {a:g}
HiddenValley:Lambda     = {lam:g}
HiddenValley:pTminFSR   = 0.5""".format(a=alpha_fsr, lam=lam)
    return """
! ---- Hidden Valley shower and hadronisation ----
HiddenValley:fragment   = on
HiddenValley:FSR        = on
{alpha}
HiddenValley:Ngauge     = {ngauge}
HiddenValley:nFlav      = {nflav}
HiddenValley:probVector = {pv:g}
""".format(alpha=alpha_lines, ngauge=ngauge, nflav=nflav, pv=prob_vector)


def hv_spectrum(m_pi, m_qv=None, m_rho=None):
    """
    Dark meson spectrum.

    With nFlav = 2 the hidden sector contains three pseudoscalars (4900111
    piv11, 4900211 piv21, 4900221 piv22) and three vectors (4900113, 4900213,
    4900223).  The off-diagonal 4900211 / 4900213 carry a conserved dark flavour
    and have *empty* decay tables in Pythia's ParticleData -- they are the
    stable dark-matter states.  We set their masses so the spectrum is
    degenerate, and mark them explicitly stable rather than relying on the empty
    table.
    """
    if m_qv is None:
        m_qv = m_pi          # constituent mass, m_rhov ~ 2 m_qv
    if m_rho is None:
        m_rho = 2.0 * m_pi
    return """
! ---- Dark sector spectrum ----
4900101:m0 = {mqv:g}       ! qv1
4900102:m0 = {mqv:g}       ! qv2
4900111:m0 = {mpi:g}       ! piv11 (diagonal, decays)
4900211:m0 = {mpi:g}       ! piv21 (off-diagonal, stable)
4900221:m0 = {mpi:g}       ! piv22 (diagonal, decays)
4900113:m0 = {mrho:g}      ! rhov11 (diagonal, decays)
4900213:m0 = {mrho:g}      ! rhov21 (off-diagonal, stable)
4900223:m0 = {mrho:g}      ! rhov22 (diagonal, decays)

! The off-diagonal (dark-flavoured) states are stable and invisible.  This is
! identical between the ee and mumu samples, so the controlled comparison is
! unaffected, but it does mean a sizeable fraction of the dark shower energy
! never returns to the SM.
4900211:mayDecay = off
4900213:mayDecay = off
""".format(mqv=m_qv, mpi=m_pi, mrho=m_rho)


def hv_decays(products, comment, tau0_mm=None):
    """
    Force every *decaying* dark meson into the same final state.

    The spec fragment only pins 4900111.  With probVector = 0.75 three quarters
    of the dark mesons are vectors, so leaving 4900113 / 4900223 on their
    default flavour-democratic tables would leave most of the visible energy
    flavour-mixed and destroy the ee vs mumu contrast.  Both the pseudoscalars
    and the vectors are therefore forced to the same channel.  meMode 91 is what
    Pythia's own piv table uses.
    """
    ids = [4900111, 4900221, 4900113, 4900223]
    lines = ["\n! ---- Dark meson decays: {0} ----".format(comment)]
    for pid in ids:
        lines.append("{0}:oneChannel = 1 1.0 91 {1}".format(pid, products))
    if tau0_mm is not None:
        lines.append("\n! ---- Proper lifetime, ctau = {0:g} mm ----".format(tau0_mm))
        lines.append("ParticleDecays:limitTau0 = off")
        for pid in ids:
            lines.append("{0}:tau0 = {1:g}".format(pid, tau0_mm))
    return "\n".join(lines) + "\n"


def zv_block(mzp):
    """q qbar -> Zv -> qv qvbar.  No UFO needed; Pythia has this natively."""
    return """
! ---- Hard process: q qbar -> Zv -> qv qvbar ----
! Pythia's native Hidden Valley Z' resonance (4900023).  This replaces the
! MadGraph 'generate p p > zp, zp > qv qv~' step in the spec: the HV module
! already implements it with exactly the 4900xxx conventions the shower expects,
! so no external Hidden Valley UFO is involved and there is no risk of an
! ID-convention mismatch between the hard process and the shower.
HiddenValley:ffbar2Zv = on
4900023:m0     = {m:g}
4900023:mWidth = {w:g}
4900023:mMin   = {mmin:g}
4900023:mMax   = {mmax:g}

! Decay only into the hidden sector (first nFlav dark quark flavours).
4900023:onMode = off
4900023:onIfMatch = 4900101 -4900101
4900023:onIfMatch = 4900102 -4900102
""".format(m=mzp, w=0.01 * mzp, mmin=0.8 * mzp, mmax=1.2 * mzp)


def higgs_portal_block(m_phi, isr_pthat=None):
    """gg -> phi (loop induced) with phi -> qv qvbar, i.e. a Higgs portal."""
    if isr_pthat is None:
        proc = """HiggsSM:gg2H = on"""
        note = """! Inclusive gg -> phi production, NO ISR requirement.  This is deliberate:
! tagging an ISR jet is exactly the trigger handle this analysis is trying to
! avoid needing (spec S1, 'Critical')."""
    else:
        proc = """HiggsSM:gg2Hg(l:t) = on
HiggsSM:qg2Hq(l:t) = on
HiggsSM:qqbar2Hg(l:t) = on
PhaseSpace:pTHatMin = {0:g}""".format(isr_pthat)
        note = """! phi + jet production with a hard recoil jet -- the ISR-tagged control (C1).
! This SHOULD fire the existing HT / single-jet seeds."""
    return """
! ---- Hard process: gg -> phi, phi -> qv qvbar (Higgs portal) ----
{note}
{proc}

25:m0     = {m:g}
25:mMin   = {mmin:g}
25:mMax   = {mmax:g}

! The portal channel is ADDED, not substituted.  gg -> phi production is a
! resonance process whose cross section Pythia builds from the dynamically
! computed phi -> g g partial width, so replacing the whole decay table with
! 'oneChannel' drives Gamma(phi->gg) -- and hence the cross section -- to zero
! ("all processes have vanishing cross sections").  Adding the channel keeps
! the SM table alive for production, and onMode/onIfMatch then leaves only the
! portal open for the decay.  meMode 102 mirrors Pythia's own Zv -> qv qvbar.
25:addChannel = 1 1.0 102 4900101 -4900101
25:onMode = off
25:onIfMatch = 4900101 -4900101
""".format(note=note, proc=proc, m=m_phi,
           mmin=0.5 * m_phi, mmax=1.5 * m_phi)


# ---------------------------------------------------------------------------
# Point definitions
# ---------------------------------------------------------------------------

LEPTON = {
    "ee":   ("11 -11", "100% -> e+ e-"),
    "mumu": ("13 -13", "100% -> mu+ mu-"),
}


# m_Zp = 200 is the primary point: it is the only place in the scan where the
# leptons are soft enough for the ee sample to plausibly sit under the
# DoubleTkElectron 25,12 floor.  It also carries the strong-coupling shower
# configuration, for the same reason.  500 and 1000 are kept on the
# specification's own shower settings as spec-faithful reference points.
S2_ALPHA_FSR = {200: 1.0, 500: None, 1000: None}


def s2_points():
    """S2: dark shower -> soft dileptons, matched ee / mumu pairs."""
    out = []
    for mzp in (200, 500, 1000):
        afsr = S2_ALPHA_FSR[mzp]
        for mpi in (2, 5):
            for flav in ("ee", "mumu"):
                name = "HVdilep_Zp{0}_piD{1}_{2}".format(mzp, mpi, flav)
                products, comment = LEPTON[flav]
                shower = ("alphaFSR = {0:g} (fixed, strong coupling)".format(afsr)
                          if afsr is not None else
                          "alphaOrder = 1, pTminFSR = 1.1 x Lambda (spec default)")
                body = (
                    HEADER.format(
                        title="S2 -- Hidden Valley dark shower to soft dileptons ({0})".format(flav),
                        subtitle="m_Zp = {0} GeV, m_piD = {1} GeV, Lambda = {1} GeV, {2}".format(
                            mzp, mpi, shower))
                    + zv_block(mzp)
                    + hv_block(lam=float(mpi), alpha_fsr=afsr)
                    + hv_spectrum(float(mpi))
                    + hv_decays(products, comment)
                )
                out.append((name, body))
    return out


def s3_points():
    """S3: displaced soft dimuons -- the S2 mumu chain with a lifetime scan."""
    out = []
    mzp, mpi = 500, 2
    products, comment = LEPTON["mumu"]
    for ctau in (1, 10, 100):
        name = "HVdilep_Zp{0}_piD{1}_mumu_ctau{2}mm".format(mzp, mpi, ctau)
        body = (
            HEADER.format(
                title="S3 -- Displaced soft dimuons, ctau = {0} mm".format(ctau),
                subtitle="Identical to HVdilep_Zp{0}_piD{1}_mumu except for the dark meson proper lifetime".format(mzp, mpi))
            + zv_block(mzp)
            + hv_block(lam=float(mpi))
            + hv_spectrum(float(mpi))
            + hv_decays(products, comment, tau0_mm=float(ctau))
        )
        out.append((name, body))
    return out


def s1_points():
    """S1 approximation: soft high-multiplicity hadronic via a Higgs portal."""
    out = []
    # Dark mesons -> light SM hadrons.  m_X = 2 GeV cannot reach b bbar, so the
    # default (b-dominated) piv table is replaced by light quarks.
    had = ("\n! ---- Dark meson decays: generic hadronic (light quarks) ----\n"
           "4900111:oneChannel = 1 1.0 91 3 -3\n"
           "4900221:oneChannel = 1 1.0 91 3 -3\n"
           "4900113:oneChannel = 1 0.34 91 1 -1\n"
           "4900113:addChannel = 1 0.33 91 2 -2\n"
           "4900113:addChannel = 1 0.33 91 3 -3\n"
           "4900223:oneChannel = 1 0.34 91 1 -1\n"
           "4900223:addChannel = 1 0.33 91 2 -2\n"
           "4900223:addChannel = 1 0.33 91 3 -3\n")

    for m_phi, lam in ((125, 1.0), (125, 2.0), (400, 2.0), (400, 4.0)):
        name = "SUEPlike_HV_mPhi{0}_mX2_Lam{1:g}".format(m_phi, lam)
        body = (
            HEADER.format(
                title="S1 (APPROXIMATION) -- soft high-multiplicity hadronic, Higgs portal",
                subtitle="m_phi = {0} GeV, m_X = 2 GeV, Lambda = {1:g} GeV -- NOT a thermal SUEP shower, see README".format(m_phi, lam))
            + higgs_portal_block(float(m_phi))
            + hv_block(lam=lam)
            + hv_spectrum(2.0)
            + had
        )
        out.append((name, body))

    # C1: the same model with a hard ISR jet required.
    name = "SUEPlike_HV_mPhi125_mX2_Lam2_ISR"
    body = (
        HEADER.format(
            title="C1 (CONTROL) -- ISR-tagged soft high-multiplicity hadronic",
            subtitle="m_phi = 125 GeV, m_X = 2 GeV, Lambda = 2 GeV, pThat > 150 GeV recoil jet")
        + higgs_portal_block(125.0, isr_pthat=150.0)
        + hv_block(lam=2.0)
        + hv_spectrum(2.0)
        + had
    )
    out.append((name, body))
    return out


# h -> a a decay modes.  Each entry is (products, short label, description).
HAA_MODES = {
    "4b":     ("5 -5",   "b bbar",     "a -> b bbar"),
    "4tau":   ("15 -15", "tau+ tau-",  "a -> tau+ tau-"),
    "4gamma": ("22 22",  "gamma gamma", "a -> gamma gamma"),
}

# (mode, masses, primary mass used for the lifetime scan or None for prompt only)
HAA_POINTS = [
    # m_a must clear 2 m_b ~ 9.4 GeV for the 4b mode.
    ("4b",     (15, 30, 60), 30),
    ("4tau",   (5, 10, 15),  10),
    # a -> gamma gamma stays open at any mass; very light a gives a collimated
    # photon pair that reconstructs as a single EM object.
    ("4gamma", (1, 5, 10),   None),
]

HAA_CTAUS = (1, 10, 100)


def haa_card(mode, ma, ctau_mm=None):
    products, _, desc = HAA_MODES[mode]
    if ctau_mm is None:
        life = ("36:mWidth = 0.001\n36:doForceWidth = on\n36:tau0   = 0.\n", "prompt")
    else:
        # The lifetime MUST be set through the width.  36 is a resonance and
        # doForceWidth is on, so Pythia derives tau0 = hbar / Gamma at
        # initialisation and silently overwrites any tau0 set by hand -- setting
        # '36:tau0' alone produces a sample that is prompt despite asking for a
        # displacement.  Setting Gamma = hbar*c / ctau makes the two consistent;
        # tau0 is set as well so the card is self-documenting.
        width = CTAU_MM_TO_WIDTH / ctau_mm
        life = (
            "! Proper lifetime, ctau = {c:g} mm, imposed through the WIDTH:\n"
            "!     Gamma[GeV] = hbar*c / ctau[mm] = 1.973e-13 / ctau\n"
            "! Setting 36:tau0 on its own does NOT work -- 36 is a resonance with\n"
            "! doForceWidth on, so Pythia recomputes tau0 from mWidth at init.\n"
            "! limitTau0 must also be off, or Pythia refuses to decay anything with\n"
            "! tau0 above its default 10 mm ceiling and the a becomes invisible.\n"
            "ParticleDecays:limitTau0 = off\n"
            "36:mWidth = {w:.4e}\n"
            "36:doForceWidth = on\n"
            "36:tau0   = {c:g}\n".format(c=ctau_mm, w=width),
            "ctau = {0:g} mm".format(ctau_mm),
        )
    return (
        HEADER.format(
            title="h -> a a -> {0} ({1})".format(mode, desc),
            subtitle="m_h = 125 GeV, m_a = {0} GeV, {1}, {2}".format(ma, desc, life[1]))
        + """
! ---- Hard process: gg -> h, h -> a a ----
! Handled entirely in Pythia's decay tables, so no 2HDM+S UFO is needed.
! meMode 100 is required: both 25 and 36 are resonances, and for a resonance a
! branching ratio cannot be overridden without meMode >= 100.
!
! Both exotic channels are ADDED rather than substituted: gg -> h production is
! built from the dynamically computed h -> g g partial width, and 'oneChannel'
! would zero it out along with the rest of the SM table, aborting the run with
! "all processes have vanishing cross sections".
HiggsSM:gg2H = on

25:m0     = 125.0
25:mMin   = 100.0
25:mMax   = 150.0
25:addChannel = 1 1.0 100 36 36
25:onMode = off
25:onIfMatch = 36 36

36:m0     = {ma:g}
36:mMin   = {mmin:g}
36:mMax   = {mmax:g}
{life}36:addChannel = 1 1.0 100 {prod}
36:onMode = off
36:onIfMatch = {prod}
""".format(ma=float(ma), mmin=0.5 * ma, mmax=1.5 * ma,
           life=life[0], prod=products)
    )


def s4_points():
    """h -> a a with a -> bb / tautau / gammagamma, prompt and displaced."""
    out = []
    for mode, masses, primary in HAA_POINTS:
        for ma in masses:
            out.append(("hToAA_{0}_ma{1}".format(mode, ma), haa_card(mode, ma)))
        if primary is not None:
            for ctau in HAA_CTAUS:
                out.append((
                    "hToAA_{0}_ma{1}_ctau{2}mm".format(mode, primary, ctau),
                    haa_card(mode, primary, ctau_mm=ctau)))
    return out


def c3_points():
    """C3: low-mass dijet resonance that the existing seeds already cover."""
    name = "Zprime_qq_m500"
    body = (
        HEADER.format(
            title="C3 (CONTROL) -- low-mass dijet resonance",
            subtitle="Sequential Z' at 500 GeV decaying to light quarks; two ~250 GeV jets")
        + """
! ---- Hard process: q qbar -> Z' -> q qbar ----
! Two ~250 GeV jets clear both SinglePuppiJet 230 and PuppiHT 450 comfortably.
! This is the 'AD should not claim credit here' control.
NewGaugeBoson:ffbar2gmZZprime = on
Zprime:gmZmode = 3

32:m0     = 500.0
32:mWidth = 5.0
32:mMin   = 400.0
32:mMax   = 600.0

32:onMode = off
32:onIfAny = 1 2 3 4 5
"""
    )
    return [(name, body)]


# ---------------------------------------------------------------------------
# MadGraph point: S5 stealth SUSY / light RPV cascade
# ---------------------------------------------------------------------------

RPV_PROC_CARD = """import model RPVMSSM_UFO

define sq = ur ul cr cl dr dl sr sl
define sq~ = ur~ ul~ cr~ cl~ dr~ dl~ sr~ sl~

generate p p > sq sq~

output _OUTDIR_
"""


def rpv_run_card(nevents_placeholder="_NEVENTS_", time_of_flight="-1.0"):
    """
    Run card with every pT / dR / mass cut zeroed and MLM matching OFF.

    The repo's existing cards ship ickkw = 1 with xqcut = 20 and ptj1min = 10.
    Spec section 4 explicitly forbids MLM here (a low xqcut in this regime is
    unstable), and ptj1min = 10 would bias a signal whose jets are 10-30 GeV.
    Both are therefore overridden, and the conflict is flagged in the point
    README as the spec asks.
    """
    return """#*********************************************************************
# AIDA-Scout S5 run card.  Derived from the repo's standard run card with
# ickkw / xqcut / ptj1min forced off -- see spec section 4.
#*********************************************************************
  RPV       = run_tag ! name of the run
  {nev} = nevents ! Number of unweighted events requested
  _ISEED_   = iseed   ! rnd seed (0=assigned automatically=default))
     1        = lpp1    ! beam 1 type
     1        = lpp2    ! beam 2 type
     7000.0     = ebeam1  ! beam 1 total energy in GeV
     7000.0     = ebeam2  ! beam 2 total energy in GeV
     nn23lo1    = pdlabel     ! PDF set
     230000    = lhaid     ! if pdlabel=lhapdf, this is the lhapdf number
 False = fixed_ren_scale  ! if .true. use fixed ren scale
 False        = fixed_fac_scale  ! if .true. use fixed fac scale
 91.188  = scale            ! fixed ren scale
 91.188  = dsqrt_q2fact1    ! fixed fact scale for pdf1
 91.188  = dsqrt_q2fact2    ! fixed fact scale for pdf2
 -1 = dynamical_scale_choice ! Choose one of the preselected dynamical choices
 1.0  = scalefact        ! scale factor for event-by-event scales
  False     = gridpack  !True = setting up the grid pack
  {tof} = time_of_flight ! threshold (in mm) below which the invariant livetime is not written
  3.0 = lhe_version       ! Change the way clustering information pass to shower.
  True = clusinfo         ! include clustering tag in output
  average =  event_norm       ! average/sum. Normalization of the weight in the LHEF
 0 = ickkw            ! 0 no matching, 1 MLM   <-- MLM OFF, see spec section 4
 1.0 = alpsfact         ! scale factor for QCD emission vx
 False = chcluster        ! cluster only according to channel diag
 5 = asrwgtflavor     ! highest quark flavor for a_s reweight
 True  = auto_ptj_mjj  ! Automatic setting of ptj and mjj if xqcut >0
 False        = pdfwgt           ! for ickkw=1, perform pdf reweighting
 0.0 = xqcut   ! minimum kt jet measure between partons   <-- no merging scale
   0  = nhel          ! using helicities importance sampling or not.
 None = bias_module  ! Bias type of bias, [None, ptj_bias, -custom_folder-]
 {{}} = bias_parameters ! Specifies the parameters of the module.
  15.0  = bwcutoff      ! (M+/-bwcutoff*Gamma)
   False  = cut_decays    ! Cut decay products
 0.0  = ptj       ! minimum pt for the jets
 0.0  = ptb       ! minimum pt for the b
 0.0  = pta       ! minimum pt for the photons
 0.0  = ptl       ! minimum pt for the charged leptons
 0.0  = misset    ! minimum missing Et (sum of neutrino's momenta)
 -1.0  = ptjmax    ! maximum pt for the jets
 -1.0  = ptbmax    ! maximum pt for the b
 -1.0  = ptamax    ! maximum pt for the photons
 -1.0  = ptlmax    ! maximum pt for the charged leptons
 -1.0  = missetmax ! maximum missing Et (sum of neutrino's momenta)
 {{}} = pt_min_pdg ! pt cut for other particles (use pdg code).
 {{}}	= pt_max_pdg ! pt cut for other particles
  0.0  = ej     ! minimum E for the jets
  0.0  = eb     ! minimum E for the b
  0.0  = ea     ! minimum E for the photons
  0.0  = el     ! minimum E for the charged leptons
  -1.0   = ejmax ! maximum E for the jets
 -1.0   = ebmax ! maximum E for the b
 -1.0   = eamax ! maximum E for the photons
 -1.0   = elmax ! maximum E for the charged leptons
 {{}} = e_min_pdg ! E cut for other particles (use pdg code).
 {{}} = e_max_pdg ! E cut for other particles
  -1.0 = etaj    ! max rap for the jets
  -1.0  = etab    ! max rap for the b
 -1  = etaa    ! max rap for the photons
 -1  = etal    ! max rap for the charged leptons
 0.0  = etajmin ! min rap for the jets
 0.0  = etabmin ! min rap for the b
 0.0  = etaamin ! min rap for the photons
 0.0  = etalmin ! main rap for the charged leptons
 {{}} = eta_min_pdg ! rap cut for other particles (use pdg code).
 {{}} = eta_max_pdg ! rap cut for other particles
 0.0 = drjj    ! min distance between jets
 0.0   = drbb    ! min distance between b's
 0.0 = drll    ! min distance between leptons
 0.0 = draa    ! min distance between gammas
 0.0   = drbj    ! min distance between b and jet
 0.0 = draj    ! min distance between gamma and jet
 0.0 = drjl    ! min distance between jet and lepton
 0.0   = drab    ! min distance between gamma and b
 0.0   = drbl    ! min distance between b and lepton
 0.0 = dral    ! min distance between gamma and lepton
 -1.0  = drjjmax ! max distance between jets
 -1.0  = drbbmax ! max distance between b's
 -1.0  = drllmax ! max distance between leptons
 -1.0  = draamax ! max distance between gammas
 -1.0  = drbjmax ! max distance between b and jet
 -1.0  = drajmax ! max distance between gamma and jet
 -1.0  = drjlmax ! max distance between jet and lepton
 -1.0  = drabmax ! max distance between gamma and b
 -1.0  = drblmax ! max distance between b and lepton
 -1.0  = dralmax ! maxdistance between gamma and lepton
 0.0   = mmjj    ! min invariant mass of a jet pair
 0.0   = mmbb    ! min invariant mass of a b pair
 0.0   = mmaa    ! min invariant mass of gamma gamma pair
 0.0   = mmll    ! min invariant mass of l+l- (same flavour) lepton pair
 -1.0  = mmjjmax ! max invariant mass of a jet pair
 -1.0  = mmbbmax ! max invariant mass of a b pair
 -1.0  = mmaamax ! max invariant mass of gamma gamma pair
 -1.0  = mmllmax ! max invariant mass of l+l- (same flavour) lepton pair
 {{}} = mxx_min_pdg ! min invariant mass of a pair of particles X/X~
 {{'default': False}} = mxx_only_part_antipart !
 0.0   = mmnl    ! min invariant mass for all letpons (l+- and vl)
 -1.0  = mmnlmax ! max invariant mass for all letpons (l+- and vl)
 0.0   = ptllmin  ! Minimum pt for 4-momenta sum of leptons(l and vl)
 -1.0  = ptllmax  ! Maximum pt for 4-momenta sum of leptons(l and vl)
 0.0  = ptheavy   ! minimum pt for at least one heavy final state
 0.0  = xptj ! minimum pt for at least one jet
 0.0  = xptb ! minimum pt for at least one b
 0.0  = xpta ! minimum pt for at least one photon
 0.0  = xptl ! minimum pt for at least one charged lepton
 0.0   = ptj1min ! minimum pt for the leading jet in pt   <-- zeroed
 0.0   = ptj2min ! minimum pt for the second jet in pt
 0.0   = ptj3min ! minimum pt for the third jet in pt
 0.0   = ptj4min ! minimum pt for the fourth jet in pt
 -1.0  = ptj1max ! maximum pt for the leading jet in pt
 -1.0  = ptj2max ! maximum pt for the second jet in pt
 -1.0  = ptj3max ! maximum pt for the third jet in pt
 -1.0  = ptj4max ! maximum pt for the fourth jet in pt
 0   = cutuse  ! reject event if fails any (0) / all (1) jet pt cuts
 0.0   = ptl1min ! minimum pt for the leading lepton in pt
 0.0   = ptl2min ! minimum pt for the second lepton in pt
 0.0   = ptl3min ! minimum pt for the third lepton in pt
 0.0   = ptl4min ! minimum pt for the fourth lepton in pt
 -1.0  = ptl1max ! maximum pt for the leading lepton in pt
 -1.0  = ptl2max ! maximum pt for the second lepton in pt
 -1.0  = ptl3max ! maximum pt for the third lepton in pt
 -1.0  = ptl4max ! maximum pt for the fourth lepton in pt
 0.0   = htjmin ! minimum jet HT=Sum(jet pt)
 -1.0  = htjmax ! maximum jet HT=Sum(jet pt)
 0.0   = ihtmin  !inclusive Ht for all partons (including b)
 -1.0  = ihtmax  !inclusive Ht for all partons (including b)
 0.0   = ht2min ! minimum Ht for the two leading jets
 0.0   = ht3min ! minimum Ht for the three leading jets
 0.0   = ht4min ! minimum Ht for the four leading jets
 -1.0  = ht2max ! maximum Ht for the two leading jets
 -1.0  = ht3max ! maximum Ht for the three leading jets
 -1.0  = ht4max ! maximum Ht for the four leading jets
 0.0 = ptgmin ! Min photon transverse momentum
 0.4 = R0gamma ! Radius of isolation code
 1.0 = xn ! n parameter of eq.(3.4) in hep-ph/9801442
 1.0 = epsgamma ! epsilon_gamma parameter of eq.(3.4) in hep-ph/9801442
 True = isoEM ! isolate photons from EM energy (photons and leptons)
 0.0   = xetamin ! minimum rapidity for two jets in the WBF case
 0.0   = deltaeta ! minimum rapidity for two jets in the WBF case
 -1.0  =  ktdurham
 0.4   =  dparameter
 -1.0  =  ptlund
 1, 2, 3, 4, 5, 6, 21  =  pdgs_for_merging_cut ! PDGs for two cuts above
 5 = maxjetflavor    ! Maximum jet pdg code
   True  = use_syst      ! Enable systematics studies
""".format(nev=nevents_placeholder, tof=time_of_flight)


def rpv_customize(m_squark):
    """
    Compressed RPV spectrum with lambda'' UDD decays.

    The squark is the LSP-adjacent state and decays directly through the UDD
    operator to two light jets, so there is no MET and no long cascade of hard
    objects -- the jets are soft simply because the parent is light and the
    decay is 2-body into quarks.  Neutralino and gluino are pushed above the
    squark so squark pair production dominates.
    """
    heavy = m_squark + 200.0
    return """# AIDA-Scout S5: compressed light-squark RPV UDD spectrum.
# Right-handed up/charm/down/strange squarks degenerate at {m:g} GeV; everything
# else decoupled so that p p > sq sq~ dominates and each squark decays via the
# lambda'' UDD operator into two light quarks.
set param_card mass 1000001 {m:g}
set param_card mass 1000002 {m:g}
set param_card mass 1000003 {m:g}
set param_card mass 1000004 {m:g}
set param_card mass 2000001 {m:g}
set param_card mass 2000002 {m:g}
set param_card mass 2000003 {m:g}
set param_card mass 2000004 {m:g}

# Third generation squarks and the gluino out of reach.
set param_card mass 1000005 {heavy:g}
set param_card mass 1000006 {heavy:g}
set param_card mass 2000005 {heavy:g}
set param_card mass 2000006 {heavy:g}
set param_card mass 1000021 {heavy:g}

# Gauginos decoupled ABOVE the squark.  This is essential, not cosmetic: with
# the UFO defaults the neutralino sits near 100 GeV and the squarks decay
# predominantly to q + neutralino/chargino, which produces exactly the MET that
# S5 is supposed not to have (measured before this was set: BR(dl -> b n2) = 1.0,
# BR(ul -> b x1+) = 0.26).  Pushing them above the squark closes those channels
# and leaves only the RPV UDD decay open.
set param_card mass 1000022 {heavy:g}
set param_card mass 1000023 {heavy:g}
set param_card mass 1000024 {heavy:g}
set param_card mass 1000025 {heavy:g}
set param_card mass 1000035 {heavy:g}
set param_card mass 1000037 {heavy:g}

# lambda'' UDD couplings, block RVLAMUDD, indices ijk of lambda''_ijk U_i D_j D_k
# (antisymmetric in the last two).
#
# The UFO ships **0.2 on every entry**, which is not a harmless default: leaving
# it in place opens decays into the third generation, and a 300 GeV squark then
# decays to a top (measured: modes -3 -6 and -5 -6 on the 2000001 squark). S5
# calls for decays to *light* quarks, so every entry is zeroed first and only
# lambda''_112 (u d s -- the sole combination with all indices in the first two
# generations) is switched back on.
set param_card rvlamudd 1 1 3 0.0
set param_card rvlamudd 1 2 3 0.0
set param_card rvlamudd 1 3 1 0.0
set param_card rvlamudd 1 3 2 0.0
set param_card rvlamudd 2 1 2 0.0
set param_card rvlamudd 2 1 3 0.0
set param_card rvlamudd 2 2 1 0.0
set param_card rvlamudd 2 2 3 0.0
set param_card rvlamudd 2 3 1 0.0
set param_card rvlamudd 2 3 2 0.0
set param_card rvlamudd 3 1 2 0.0
set param_card rvlamudd 3 1 3 0.0
set param_card rvlamudd 3 2 1 0.0
set param_card rvlamudd 3 2 3 0.0
set param_card rvlamudd 3 3 1 0.0
set param_card rvlamudd 3 3 2 0.0

# The only surviving coupling: u d s.  1e-2 keeps the decay prompt on detector
# scales while leaving the squark narrow.
set param_card rvlamudd 1 1 2 1.0e-2
set param_card rvlamudd 1 2 1 -1.0e-2

# Recompute the squark widths so the RPV UDD channel is present in the decay
# table that gets written into the LHE header and handed to Pythia.  Without
# this the squarks inherit the UFO's default table and may not decay to
# two quarks at all.
compute_widths 1000001 1000002 1000003 1000004 2000001 2000002 2000003 2000004
""".format(m=m_squark, heavy=heavy)


def rpv_points():
    out = []
    for m in (300, 600):
        name = "RPV_squark{0}_UDD".format(m)
        out.append((name, float(m)))
    return out


# ---------------------------------------------------------------------------
# S5 cascade variant: squark -> quark + LSP, LSP -> three light quarks.
#
# The direct two-body RPV decay above gives only 4 jets.  The specification asks
# for 8-12 jets of 10-30 GeV, which needs one more step in the chain.
#
# Two hard constraints shape the mass points, both physical rather than
# technical:
#
#   1. RPV has no invisible particle, so the *entire* parent mass is converted
#      into visible jets: HT_true = 2 x m_squark.  For N jets of average energy
#      E that fixes 2 x m_squark = N x E.  N = 10 jets at 20-30 GeV therefore
#      requires m_squark ~ 100-150 GeV -- the specification's 300/600 GeV cannot
#      produce 10-30 GeV jets under any topology.
#   2. The quark from squark -> quark + LSP is hard unless the spectrum is
#      compressed, so m_LSP must sit close under m_squark.
#
# The cascade is put in the MATRIX ELEMENT rather than in decay tables.  MG5's
# compute_widths zeroes every partial width below the QCD scale (~0.2 GeV), and
# a light RPV LSP decaying through lambda'' = 1e-2 is far below that -- the LSP
# came back with width exactly 0, i.e. stable.  Letting Pythia recompute the
# widths instead failed differently (invalid particle codes out of the RPV
# machinery on this UFO).  Generating the decays in the matrix element sidesteps
# both: the LHE is already fully decayed and no decay table is consulted.
RPV_CASCADE_PROC_CARD = """import model RPVMSSM_UFO

# Squark pair with the full cascade in the matrix element:
#   ur     -> u  + n1,  n1 -> u  d  s     (lambda''_112 UDD)
#   ur~    -> u~ + n1,  n1 -> u~ d~ s~
# Eight partons at the hard-process level.  Restricted to the right-handed up
# squark, the only flavour lambda''_112 couples to; see the point README for why
# the decays are here rather than in the decay table.

generate p p > ur ur~, (ur > u n1, n1 > u d s), (ur~ > u~ n1, n1 > u~ d~ s~)

output _OUTDIR_
"""


def rpv_cascade_customize(m_squark, m_lsp):
    heavy = m_squark + 400.0
    return """# AIDA-Scout S5 cascade: m_squark = {m:g} GeV, m_LSP = {y:g} GeV.
# Compressed by {d:g} GeV so the quark from squark -> quark + LSP stays soft.
set param_card mass 1000001 {m:g}
set param_card mass 1000002 {m:g}
set param_card mass 1000003 {m:g}
set param_card mass 1000004 {m:g}
set param_card mass 2000001 {m:g}
set param_card mass 2000002 {m:g}
set param_card mass 2000003 {m:g}
set param_card mass 2000004 {m:g}

# Third generation, gluino and the heavier gauginos decoupled.
set param_card mass 1000005 {h:g}
set param_card mass 1000006 {h:g}
set param_card mass 2000005 {h:g}
set param_card mass 2000006 {h:g}
set param_card mass 1000021 {h:g}
set param_card mass 1000023 {h:g}
set param_card mass 1000024 {h:g}
set param_card mass 1000025 {h:g}
set param_card mass 1000035 {h:g}
set param_card mass 1000037 {h:g}

# The LSP.
set param_card mass 1000022 {y:g}

# lambda''_112 only -- decays to light quarks, no third generation.  The UFO
# ships 0.2 on every RVLAMUDD entry; the others are irrelevant here because the
# matrix element only contains the 112 vertex, but the value still sets the
# overall normalisation of the LSP decay.
set param_card rvlamudd 1 1 2 1.0e-2
set param_card rvlamudd 1 2 1 -1.0e-2

# Explicit non-zero widths, required or MG5 cannot build the propagator in the
# decay chain.
#
# WARNING -- THESE INVALIDATE THE CROSS SECTION MG5 REPORTS.  For a decay chain
# MG5 forms sigma = sigma_production x Gamma_partial / Gamma_total, so supplying
# Gamma_total by hand makes the reported number arbitrary.  Measured symptom:
# the quoted cross section is NOT monotonic in the squark mass (13.42 pb at
# m = 150 against 0.0998 pb at m = 120), which is backwards for production and is
# the artifact, not physics.
#
# Normalise instead as
#     sigma_sample = sigma(p p > ur ur~) x BR(cascade)
# with BR(cascade) = 1 to a good approximation here: only lambda''_112 is on and
# the LSP sits below the squark, so the cascade is effectively the only channel.
# Generate 'p p > ur ur~' on its own to get the production cross section.
set param_card decay 1000002 1.5
set param_card decay 2000002 1.5
set param_card decay 1000022 0.1
""".format(m=m_squark, y=m_lsp, d=m_squark - m_lsp, h=heavy)


def rpv_cascade_points():
    """(m_squark, m_LSP): the specification's masses plus the light points that
    can actually reach 8-12 jets of 10-30 GeV."""
    return [(300.0, 250.0), (600.0, 550.0), (150.0, 100.0), (120.0, 90.0)]


# ---------------------------------------------------------------------------
# S5b: RPV electroweakinos -- the non-excluded companion to the light squark.
#
# The 150 GeV squark point above reproduces the target signature but is ruled out
# by existing LHC searches.  A light electroweakino multiplet is not: it is
# produced electroweakly, so the cross section is O(pb) rather than the ~1600 pb
# of 150 GeV squarks, and the RPV multijet searches that exclude light squarks
# are driven by strong production and have very little reach against it.  LEP
# sets m_chargino >~ 92-103 GeV, which is the binding constraint.
#
# Topology: each electroweakino decays to three quarks through lambda'', so pair
# production gives SIX jets rather than the squark cascade's eight.  Fewer jets,
# but the jet energies land better -- at m = 150 GeV the six jets average ~25 GeV
# and therefore sit mostly BELOW the 30 GeV HT-constituent threshold, so the menu
# HT is close to zero by construction.
RPV_EWKINO_PROC_CARD = """import model RPVMSSM_UFO

# Light Higgsino multiplet with RPV UDD decays through the THIRD generation.
#
# lambda''_323 (t s b) is the right operator for a Higgsino: the chi-t-stop
# vertex goes through the TOP Yukawa, which is large, so the decay is prompt and
# unsuppressed.  lambda''_112 would not work here -- a pure Higgsino couples to a
# quark and a squark through that quark's Yukawa, so decays to light quarks are
# Yukawa-suppressed to the point of being non-prompt.  Allowing heavy flavour is
# what makes a genuine pure-Higgsino benchmark possible.
#
# It also buys jet multiplicity: n1 > t s b with a hadronic top gives FIVE jets
# per neutralino rather than three, so the pair lands at 8-10 jets instead of 6.
#
# The top is left undecayed in the matrix element and handed to Pythia -- its
# width is large and standard, so it has none of the RPV width problems.  The
# electroweakino decays stay in the matrix element for the usual reason: their
# lambda'' widths are far below the QCD scale and MG5's compute_widths would
# zero them, leaving the LSP stable.

define q3 = t t~ b b~ s s~

generate    p p > n1 x1+, (n1 > q3 q3 q3), (x1+ > q3 q3 q3)
add process p p > n1 x1-, (n1 > q3 q3 q3), (x1- > q3 q3 q3)
add process p p > x1+ x1-, (x1+ > q3 q3 q3), (x1- > q3 q3 q3)

output _OUTDIR_
"""


def rpv_ewkino_customize(m_ewkino):
    """
    Near-degenerate Higgsino multiplet at m_ewkino, everything else heavy,
    decaying through lambda''_323 (t s b).

    Mass points are chosen so the top is on shell: m >= ~180 GeV.  Below that the
    t s b mode closes and the decay becomes four-body through an off-shell top,
    which is strongly suppressed and gives a long-lived Higgsino -- a displaced
    multijet signature rather than a prompt one.  That is a legitimate signal in
    its own right (and overlaps with the S3 displacement theme) but it is a
    different sample, so it is not mixed in here.
    """
    heavy = 1000.0
    return """# AIDA-Scout S5b: light RPV Higgsino multiplet at {m:g} GeV.
# Non-excluded companion to RPV_squark150_cascade_LSP100: electroweak production
# keeps this out of reach of the RPV multijet searches that exclude light squarks.
#
# Decays through lambda''_323 (t s b).  The chi-t-stop vertex uses the top
# Yukawa, so a pure Higgsino decays promptly here -- which is exactly why heavy
# flavour matters: with lambda''_112 the same state would be Yukawa-suppressed
# and non-prompt.

# The near-degenerate multiplet.
set param_card mass 1000022 {m:g}
set param_card mass 1000023 {m1:g}
set param_card mass 1000024 {m1:g}

# Everything else decoupled: squarks only appear off-shell in the RPV decay.
set param_card mass 1000025 {h:g}
set param_card mass 1000035 {h:g}
set param_card mass 1000037 {h:g}
set param_card mass 1000021 {h:g}
set param_card mass 1000001 {h:g}
set param_card mass 1000002 {h:g}
set param_card mass 1000003 {h:g}
set param_card mass 1000004 {h:g}
set param_card mass 1000005 {h:g}
set param_card mass 1000006 {h:g}
set param_card mass 2000001 {h:g}
set param_card mass 2000002 {h:g}
set param_card mass 2000003 {h:g}
set param_card mass 2000004 {h:g}
set param_card mass 2000005 {h:g}
set param_card mass 2000006 {h:g}

# lambda''_323 (t s b) only -- the third-generation operator a Higgsino can
# actually use.  Every other RVLAMUDD entry is zeroed: the UFO ships 0.2 on all
# of them, which would otherwise reopen the light-flavour modes.
set param_card rvlamudd 1 1 2 0.0
set param_card rvlamudd 1 1 3 0.0
set param_card rvlamudd 1 2 1 0.0
set param_card rvlamudd 1 2 3 0.0
set param_card rvlamudd 1 3 1 0.0
set param_card rvlamudd 1 3 2 0.0
set param_card rvlamudd 2 1 2 0.0
set param_card rvlamudd 2 1 3 0.0
set param_card rvlamudd 2 2 1 0.0
set param_card rvlamudd 2 2 3 0.0
set param_card rvlamudd 2 3 1 0.0
set param_card rvlamudd 2 3 2 0.0
set param_card rvlamudd 3 1 2 0.0
set param_card rvlamudd 3 1 3 0.0
set param_card rvlamudd 3 3 1 0.0

# The surviving coupling and its antisymmetric partner.
set param_card rvlamudd 3 2 3 1.0e-2
set param_card rvlamudd 3 3 2 -1.0e-2

# Non-zero widths for the propagators in the decay chain.  As for the squark
# cascade these make MG5's reported cross section meaningless -- normalise with
# the production cross section instead (generate the production process alone).
set param_card decay 1000022 1.0e-2
set param_card decay 1000023 1.0e-2
set param_card decay 1000024 1.0e-2
""".format(m=m_ewkino, m1=m_ewkino + 1.0, h=heavy)


def rpv_ewkino_points():
    # Top on shell in n1 -> t s b, so the decay is prompt and gives 5 jets/side.
    return [200.0, 300.0]


# ---------------------------------------------------------------------------
# S5c: displaced RPV Higgsino, below the top threshold.
#
# Below ~180 GeV the lambda''_323 mode n1 -> t s b closes.  The natural operator
# that stays open is lambda''_223 (c s b): it runs off the CHARM Yukawa instead
# of the top Yukawa, which is smaller by roughly (y_c/y_t)^2 ~ 1e-5, so the
# Higgsino becomes long-lived without any tuning.  The displacement is physical,
# not imposed.
#
# HOW THE DISPLACEMENT SURVIVES THE CHAIN.  The decays are in the matrix element,
# so the daughters would normally be written at the primary vertex and all the
# displacement would be lost.  Two things prevent that:
#   * time_of_flight = 0 in the run card, so MG5 writes the invariant lifetime
#     (VTIMUP) of the intermediate resonance into the LHE, and
#   * the Higgsino width is set to hit a target ctau, using
#         ctau[mm] = hbar*c / Gamma = 1.973e-13 / Gamma[GeV].
# Pythia then propagates the resonance before decaying it, and Delphes'
# ParticlePropagator starts the daughters from the displaced vertex.
#
# Verify VTIMUP is actually non-zero in the LHE before trusting the sample --
# this is the step most likely to fail silently.
CTAU_MM_TO_WIDTH = 1.973e-13  # ctau[mm] = CTAU_MM_TO_WIDTH / Gamma[GeV]

RPV_EWKINO_DISP_PROC_CARD = """import model RPVMSSM_UFO

# Displaced light Higgsino multiplet, below the top threshold.
#
# lambda''_223 (c s b) rather than _323 (t s b): at m < m_top the t s b mode is
# closed, and the c s b mode runs off the charm Yukawa, which is small enough
# that the Higgsino is naturally long-lived.  Three jets per state, two of them
# heavy-flavour, all emerging from a displaced vertex.

define q2 = c c~ s s~ b b~

generate    p p > n1 x1+, (n1 > q2 q2 q2), (x1+ > q2 q2 q2)
add process p p > n1 x1-, (n1 > q2 q2 q2), (x1- > q2 q2 q2)
add process p p > x1+ x1-, (x1+ > q2 q2 q2), (x1- > q2 q2 q2)

output _OUTDIR_
"""


def rpv_ewkino_disp_customize(m_ewkino, ctau_mm):
    width = CTAU_MM_TO_WIDTH / ctau_mm
    heavy = 1000.0
    return """# AIDA-Scout S5c: displaced RPV Higgsino at {m:g} GeV, ctau = {c:g} mm.
#
# Below the top threshold lambda''_323 (t s b) is closed, so this point uses
# lambda''_223 (c s b), which runs off the charm Yukawa and is naturally
# long-lived.  The width below is set to hit the target ctau via
#     ctau[mm] = 1.973e-13 / Gamma[GeV]
# and the run card sets time_of_flight = 0 so MG5 writes the lifetime into the
# LHE.  To scan the lifetime, change ONLY the 1000022 width -- the process
# directory does not need regenerating.

# The near-degenerate multiplet, below the top threshold.
set param_card mass 1000022 {m:g}
set param_card mass 1000023 {m1:g}
set param_card mass 1000024 {m1:g}

# Everything else decoupled.
set param_card mass 1000025 {h:g}
set param_card mass 1000035 {h:g}
set param_card mass 1000037 {h:g}
set param_card mass 1000021 {h:g}
set param_card mass 1000001 {h:g}
set param_card mass 1000002 {h:g}
set param_card mass 1000003 {h:g}
set param_card mass 1000004 {h:g}
set param_card mass 1000005 {h:g}
set param_card mass 1000006 {h:g}
set param_card mass 2000001 {h:g}
set param_card mass 2000002 {h:g}
set param_card mass 2000003 {h:g}
set param_card mass 2000004 {h:g}
set param_card mass 2000005 {h:g}
set param_card mass 2000006 {h:g}

# lambda''_223 (c s b) only.  The UFO ships 0.2 on every RVLAMUDD entry, so all
# the others are zeroed or the light-flavour and top modes reopen.
set param_card rvlamudd 1 1 2 0.0
set param_card rvlamudd 1 1 3 0.0
set param_card rvlamudd 1 2 1 0.0
set param_card rvlamudd 1 2 3 0.0
set param_card rvlamudd 1 3 1 0.0
set param_card rvlamudd 1 3 2 0.0
set param_card rvlamudd 2 1 2 0.0
set param_card rvlamudd 2 1 3 0.0
set param_card rvlamudd 2 2 1 0.0
set param_card rvlamudd 2 3 1 0.0
set param_card rvlamudd 2 3 2 0.0
set param_card rvlamudd 3 1 2 0.0
set param_card rvlamudd 3 1 3 0.0
set param_card rvlamudd 3 2 1 0.0
set param_card rvlamudd 3 2 3 0.0
set param_card rvlamudd 3 3 1 0.0
set param_card rvlamudd 3 3 2 0.0

# The surviving coupling and its antisymmetric partner.
set param_card rvlamudd 2 2 3 1.0e-2
set param_card rvlamudd 2 3 2 -1.0e-2

# ctau = {c:g} mm.  This width is what sets the displacement; it also makes the
# cross section MG5 reports meaningless, as for every other decay-chain point.
set param_card decay 1000022 {w:.4e}
set param_card decay 1000023 {w:.4e}
set param_card decay 1000024 {w:.4e}
""".format(m=m_ewkino, m1=m_ewkino + 1.0, h=heavy, c=ctau_mm, w=width)


def rpv_ewkino_disp_points():
    """(mass, ctau_mm) below the top threshold."""
    return [(150.0, 10.0)]


# ---------------------------------------------------------------------------
# Per-point READMEs (spec deliverable 5.6)
# ---------------------------------------------------------------------------

MENU = """
| Seed | Threshold | Fires? |
|---|---|---|
| PuppiHT | 450 (constituents pT > 30) | {ht} |
| SinglePuppiJet | 230 | {jet} |
| QuadJet | 400,70,55,40,40 | {quad} |
| DoubleTkMuon (BPH) | 2,2, abs(eta)<1.5, dR<1.4, OS, dz<1cm | {bph} |
| DoubleTkMuon (central) | 4,4 | {mu44} |
| DoubleTkElectron | 25,12 | {ele} |
| DoubleTkIsoPhoton | 22,12 | {pho} |
| DoublePuppiTau | 52,52 | {tau} |
| PuppiETmiss | 200 | {met} |
"""

README_HEAD = """# {name}

**AIDA-Scout {sid}** -- generated by `make_signal_cards.py`.

{what}

## Configuration

{config}

## Why it evades (or does not evade) the Phase-2 L1 menu
{menu}
{notes}
## Running

```bash
apptainer exec --bind $simdir \\
  /cvmfs/unpacked.cern.ch/registry.hub.docker.com/jmduarte/mapyde:latest \\
  sh $simdir/run.sh {name} <nevents> <seed> $simdir False
```

This point uses the **{mode}** branch of `run.sh`.
"""


def write_readme(path, **kw):
    kw.setdefault("notes", "")
    with open(path, "w") as fh:
        fh.write(README_HEAD.format(**kw))


HV_CAVEATS = """
## Caveats specific to this chain

* **No external Hidden Valley UFO is used.** The hard process is Pythia's own
  `HiddenValley:ffbar2Zv`, so the 4900xxx identity conventions of the hard
  process and of the shower are guaranteed to agree. This resolves open item 3
  of the specification: there is no UFO/module mismatch to check.
* **`nFlav = 2` leaves roughly half the dark shower invisible.** The
  off-diagonal dark mesons `4900211` / `4900213` carry a conserved dark flavour
  and have empty decay tables; they are marked stable explicitly. Measured on a
  50-event test at m_Zp = 500 / m_piD = 2: 5.4 decaying vs 5.2 stable dark
  mesons per event. This is identical between the ee and mumu samples, so the
  controlled comparison is unaffected.
* **The vectors are forced too.** With `probVector = 0.75` three quarters of the
  dark mesons are `rhov`. The specification fragment pins only `4900111`, which
  would have left most of the visible energy on the default flavour-democratic
  table and destroyed the ee/mumu contrast. `4900113` and `4900223` are
  therefore forced to the same channel. **This is an extension of the
  specification fragment, flagged here as requested.**
* **No MLM matching**, per specification section 4. The hard process is the
  resonance only; the shower supplies all extra radiation.
"""


def s2_readme_body(mzp, mpi, flav):
    other = "ee" if flav == "mumu" else "mumu"
    if flav == "mumu":
        verdict = ("**This is the *covered* member of the pair.** The BPH "
                   "DoubleTkMuon 2,2 seed should fire in most events, which is "
                   "the point: it is the calibration/reference sample (C2 when "
                   "ctau = 0) against which the ee sample is compared.")
        bph, ele = "**YES** (by design)", "no muons -> N/A"
    else:
        verdict = ("**This is the *uncovered* member of the pair.** There is no "
                   "di-electron seed below 12 GeV, so the identical kinematics "
                   "that the mumu sample hands to the BPH seed have no "
                   "electron equivalent to catch them.")
        bph, ele = "no muons -> N/A", "**no** (leptons far below 25,12)"
    return verdict, bph, ele


def build_readmes(outdir):
    # ---- S2 ----
    for mzp in (200, 500, 1000):
        for mpi in (2, 5):
            for flav in ("ee", "mumu"):
                name = "HVdilep_Zp{0}_piD{1}_{2}".format(mzp, mpi, flav)
                verdict, bph, ele = s2_readme_body(mzp, mpi, flav)
                lep = "e+e-" if flav == "ee" else "mu+mu-"
                write_readme(
                    os.path.join(outdir, name, "README.md"),
                    name=name, sid="S2 (dark shower to soft dileptons)",
                    mode="pythia",
                    what=("A Hidden Valley Z' of {0} GeV decays to a pair of dark quarks, "
                          "which shower and hadronise in the hidden sector into dark mesons "
                          "of mass {1} GeV (vectors at {2} GeV). Every decaying dark meson "
                          "is forced to **{3}**, giving a handful of soft, collimated "
                          "leptons of a single flavour.\n\n"
                          "This point is one half of the matched ee/mumu pair: its partner is "
                          "`HVdilep_Zp{0}_piD{1}_{4}`, which is **identical in every respect "
                          "except the lepton flavour**.").format(mzp, mpi, 2 * mpi, lep, other_flav(flav)),
                    config=("* Hard process: `HiddenValley:ffbar2Zv`, m_Zp = {0} GeV\n"
                            "* Shower: {5}\n"
                            "* Lambda = {1} GeV, Ngauge = 3, nFlav = 2, probVector = 0.75\n"
                            "* m_piD = {1} GeV, m_rhoD = {3} GeV, m_qv = {1} GeV\n"
                            "* Dark meson decays: 100% -> {4}\n"
                            "* Cross section: **{6} pb** (Pythia LO, no k-factor)").format(
                                mzp, mpi, 1.1 * mpi, 2 * mpi, lep,
                                ("`alphaOrder = 0`, `alphaFSR = {0:g}`, `pTminFSR = 0.5` "
                                 "-- strong-coupling / high-multiplicity configuration, "
                                 "see below".format(S2_ALPHA_FSR[mzp])
                                 if S2_ALPHA_FSR[mzp] is not None else
                                 "`alphaOrder = 1`, `pTminFSR = 1.1 x Lambda` "
                                 "(specification default)"),
                                S2_XSEC.get((mzp, mpi, flav), "see outdir/cross_section.txt")),
                    menu=MENU.format(
                        ht="see caveat below", jet="see caveat below", quad="no",
                        bph=bph, mu44="**YES** if mumu" if flav == "mumu" else "N/A",
                        ele=ele, pho="no", tau="no", met="no"),
                    notes=HV_CAVEATS + S2_HADRONIC_WARNING)

    # ---- S3 ----
    for ctau in (1, 10, 100):
        name = "HVdilep_Zp500_piD2_mumu_ctau{0}mm".format(ctau)
        write_readme(
            os.path.join(outdir, name, "README.md"),
            name=name, sid="S3 (displaced soft dimuons)", mode="pythia",
            what=("Identical to `HVdilep_Zp500_piD2_mumu` except that every decaying "
                  "dark meson is given a proper lifetime of **ctau = {0} mm**. The "
                  "ctau = 0 reference point is `HVdilep_Zp500_piD2_mumu` itself, which "
                  "doubles as control C2.").format(ctau),
            config=("* As `HVdilep_Zp500_piD2_mumu`\n"
                    "* `4900111/4900221/4900113/4900223:tau0 = {0}` mm\n"
                    "* `ParticleDecays:limitTau0 = off` -- **required**; the default "
                    "CMS-style `tau0Max = 10 mm` would stop the dark mesons decaying "
                    "at all and make the sample silently invisible\n"
                    "* Cross section: **5.585 pb** (unchanged by the lifetime)").format(ctau),
            menu=MENU.format(ht="no", jet="no", quad="no",
                             bph="**intended: no** -- but see the blocker below",
                             mu44="**intended: no**", ele="N/A", pho="no",
                             tau="no", met="no"),
            notes=S3_BLOCKER.format(ctau=ctau) + HV_CAVEATS)

    # ---- S1 / C1 ----
    for m_phi, lam in ((125, 1.0), (125, 2.0), (400, 2.0), (400, 4.0)):
        name = "SUEPlike_HV_mPhi{0}_mX2_Lam{1:g}".format(m_phi, lam)
        write_readme(
            os.path.join(outdir, name, "README.md"),
            name=name, sid="S1 (SUEP) -- APPROXIMATION, see warning", mode="pythia",
            what=("A {0} GeV scalar is produced through gluon fusion and decays through a "
                  "Higgs portal into the hidden sector, which showers into many soft dark "
                  "mesons of mass 2 GeV that decay back to light SM quarks. The result is a "
                  "soft, high-multiplicity, all-hadronic event with no MET and no hard "
                  "jet.\n\n"
                  "Generated with **no ISR requirement**, per specification section S1 "
                  "'Critical'. The ISR-tagged version is the separate control point "
                  "`SUEPlike_HV_mPhi125_mX2_Lam2_ISR` (C1).").format(m_phi),
            config=("* Hard process: `HiggsSM:gg2H`, m_phi = {0} GeV\n"
                    "* Portal: `25:addChannel ... 4900101 -4900101`, all SM decays closed\n"
                    "* Lambda = {1:g} GeV, pTminFSR = {2:g} GeV, m_X = 2 GeV, m_rhoD = 4 GeV\n"
                    "* Dark mesons -> light quarks (s sbar for the pseudoscalars, u/d/s for "
                    "the vectors); the default table is b-dominated and inaccessible at 2 GeV\n"
                    "* Reference cross section sigma(gg -> phi) = **{3} pb** "
                    "(Pythia LO, no k-factor)\n"
                    "* **Normalisation warning:** the sigma printed by the generator is "
                    "sigma(gg->phi) multiplied by Pythia's internal open-channel fraction. "
                    "For an *added* exotic channel that fraction is a width-bookkeeping "
                    "artifact, not a physical branching ratio (it comes out ~1.4e-4 at "
                    "m_phi = 400). **Normalise as sigma(gg->phi) x BR(phi->hidden) using "
                    "the reference sigma above and your own assumed BR.**").format(
                        m_phi, lam, 1.1 * lam, GGH_XSEC[m_phi]),
            menu=MENU.format(ht="no (energy spread over many soft hadrons)",
                             jet="no", quad="no", bph="no", mu44="no", ele="no",
                             pho="no", tau="no", met="no (fully visible decay)"),
            notes=SUEP_WARNING)

    name = "SUEPlike_HV_mPhi125_mX2_Lam2_ISR"
    write_readme(
        os.path.join(outdir, name, "README.md"),
        name=name, sid="C1 (control: boosted SUEP-like with hard ISR)", mode="pythia",
        what=("The same model as `SUEPlike_HV_mPhi125_mX2_Lam2`, but produced in "
              "association with a hard recoil jet (`pTHatMin = 150` GeV). This is the "
              "negative control: it **should** be caught by the existing hadronic seeds, "
              "and if the anomaly detector flags it that must not be part of the headline "
              "sensitivity claim."),
        config=("* Hard process: `HiggsSM:gg2Hg(l:t)`, `qg2Hq(l:t)`, `qqbar2Hg(l:t)` with "
                "`PhaseSpace:pTHatMin = 150`\n"
                "* Hidden sector identical to `SUEPlike_HV_mPhi125_mX2_Lam2`\n"
                "* Reference cross section sigma(gg->phi+j, pTHat>150) = **1.945 pb** "
                "(Pythia LO); same normalisation warning as the nominal point"),
        menu=MENU.format(ht="**likely YES**", jet="**likely YES** (recoil jet ~150-250 GeV)",
                         quad="no", bph="no", mu44="no", ele="no", pho="no",
                         tau="no", met="no"),
        notes=SUEP_WARNING + C4_NOTE)

    # ---- S4 ----
    for mode, masses, primary in HAA_POINTS:
        for ma, ctau in ([(m, None) for m in masses]
                         + ([(primary, c) for c in HAA_CTAUS] if primary else [])):
            name = ("hToAA_{0}_ma{1}".format(mode, ma) if ctau is None else
                    "hToAA_{0}_ma{1}_ctau{2}mm".format(mode, ma, ctau))
            _, obj, desc = HAA_MODES[mode]
            per_obj = 125.0 / 4.0
            life = ("prompt (`tau0 = 0`)" if ctau is None else
                    "**ctau = {0:g} mm**".format(ctau))
            write_readme(
                os.path.join(outdir, name, "README.md"),
                name=name, sid="S4 (h -> a a, {0})".format(desc), mode="pythia",
                what=("A 125 GeV Higgs produced by gluon fusion decays to a pair of light "
                      "pseudoscalars of mass {0} GeV, each decaying to {1}. The final "
                      "state is four {1} objects sharing 125 GeV, so each carries roughly "
                      "{2:.0f} GeV before any further decay.{3}").format(
                          ma, obj, per_obj,
                          "" if ctau is None else
                          "\n\nThe pseudoscalar is given a proper lifetime of {0:g} mm, so "
                          "the four objects emerge from two displaced vertices. The "
                          "prompt reference is `hToAA_{1}_ma{2}`.".format(ctau, mode, ma)),
                config=("* Hard process: `HiggsSM:gg2H`, m_h = 125 GeV\n"
                        "* `25:addChannel -> 36 36`, all SM Higgs decays closed\n"
                        "* m_a = {0} GeV, `36:addChannel -> {1}`, {2}\n"
                        "* No 2HDM+S UFO is required -- this is entirely a decay-table "
                        "configuration, which is why it runs on the pythia branch\n"
                        "* Reference cross section sigma(gg->h) = **28.07 pb** (Pythia LO, "
                        "no k-factor); rescale by your assumed BR(h->aa) -- see the "
                        "normalisation warning shared with the S1 points").format(
                            ma, HAA_MODES[mode][0], life),
                menu=MENU.format(
                    ht="no", jet="no", quad="no", bph="no", mu44="no",
                    ele="no",
                    pho=("**no** -- the DoubleTkIsoPhoton 22,12 floor is above a photon "
                         "from a {0} GeV a; at low m_a the pair is collimated and "
                         "reconstructs as one object".format(ma)
                         if mode == "4gamma" else "no"),
                    tau=("**no** -- the 52,52 PuppiTau floor is far above a tau from a "
                         "125/4 GeV share" if mode == "4tau" else "no"),
                    met=("no (neutrinos partly cancel)" if mode == "4tau" else "no")),
                notes=HAA_NOTES.get(mode, "") + (
                    "" if ctau is None else HAA_DISPLACED_NOTE.format(c=ctau)))

    # ---- C3 ----
    write_readme(
        os.path.join(outdir, "Zprime_qq_m500", "README.md"),
        name="Zprime_qq_m500", sid="C3 (control: low-mass dijet resonance)",
        mode="pythia",
        what=("A 500 GeV sequential Z' decaying to light quarks, giving two jets of "
              "roughly 250 GeV each. This is the standard 'the anomaly detector should "
              "not claim credit here' control: the event is comfortably inside the "
              "existing menu."),
        config=("* Hard process: `NewGaugeBoson:ffbar2gmZZprime` with `Zprime:gmZmode = 3` "
                "(pure Z', no gamma/Z interference)\n"
                "* m_Z' = 500 GeV, decays forced to u/d/s/c/b\n"
                "* Cross section: **154.8 pb** (Pythia LO, no k-factor). This is the "
                "full sequential-Z' coupling strength and is deliberately unphysical as a "
                "signal rate -- it is a control, only the shape matters."),
        menu=MENU.format(ht="**YES** (HT ~ 500)", jet="**YES** (~250 GeV jets)",
                         quad="no", bph="no", mu44="no", ele="no", pho="no",
                         tau="no", met="no"),
        notes="")

    # ---- S5 ----
    for m in (300, 600):
        name = "RPV_squark{0}_UDD".format(m)
        write_readme(
            os.path.join(outdir, name, "README.md"),
            name=name, sid="S5 (stealth SUSY / light RPV cascade)", mode="madgraph",
            what=("Pair production of degenerate light squarks at {0} GeV, each decaying "
                  "through the R-parity-violating lambda'' UDD operator directly into two "
                  "light quarks. The result is a high-multiplicity all-hadronic event with "
                  "**no MET** -- a different menu failure mode from S1: high multiplicity "
                  "but *not* isotropic.").format(m),
            config=("* Model: `RPVMSSM_UFO` (already present in the container's MG5 "
                    "installation -- no download needed)\n"
                    "* `generate p p > sq sq~` over the eight light-flavour squarks\n"
                    "* m_squark = {0} GeV, gluino/gauginos/3rd generation decoupled at "
                    "{1} GeV so squark pair production dominates and no MET is produced\n"
                    "* lambda'' UDD couplings 1e-2 (prompt, but narrow)\n"
                    "* **run_card deviates from the repo convention:** `ickkw = 0`, "
                    "`xqcut = 0`, `ptj1min = 0`. The repo's standard cards ship "
                    "`ickkw = 1 / xqcut = 20 / ptj1min = 10`; specification section 4 "
                    "forbids MLM here and a 10 GeV leading-jet cut would bias a signal "
                    "whose jets are 10-30 GeV. **Conflict flagged rather than silently "
                    "followed, as requested.**\n"
                    "* Cross section: taken from the MG5 run output (`run_01` banner)").format(
                        m, m + 200),
            menu=MENU.format(ht="**borderline** -- verify per point; target is HT < 450",
                             jet="no (target 10-30 GeV jets)", quad="**possibly** -- verify",
                             bph="no", mu44="no", ele="no", pho="no", tau="no",
                             met="no (RPV: no LSP escapes)"),
            notes=("\n## Validation status\n\n"
                   "**Partially validated. Do not use without the checks below.**\n\n"
                   "What was confirmed on a 200-event test at m_squark = 300 GeV:\n\n"
                   "* The `RPVMSSM_UFO` process builds (76 subprocesses) and integrates; "
                   "sigma(p p > sq sq~) = **70.67 +- 0.13 pb** at m_squark = 300 GeV.\n"
                   "* `set param_card mass ...` is accepted for the squarks (the mass "
                   "block is an input in this UFO).\n"
                   "* `compute_widths` does populate the RPV UDD channels: the squark "
                   "decay table contains the two-quark modes `-3 -1`, `-5 -1`, `-5 -3`.\n\n"
                   "What was found and fixed: with the UFO's default spectrum the "
                   "neutralino sits near 100 GeV and the squarks decay mostly to "
                   "q + neutralino/chargino -- `BR(dl -> b n2) = 1.0` and "
                   "`BR(ul -> b x1+) = 0.26` were measured. That is exactly the MET S5 is "
                   "supposed not to have. The customizecards now decouple all gauginos "
                   "above the squark to close those channels.\n\n"
                   "A second round of testing after the gaugino fix confirmed the squarks "
                   "then decay **100% to two quarks with no neutralino/chargino channels** "
                   "(sigma = 70.23 +- 0.12 pb), but exposed two further problems, now "
                   "addressed in the customizecards and **not yet re-tested**:\n\n"
                   "* The UFO ships lambda'' = 0.2 on *every* RVLAMUDD entry. That opened "
                   "third-generation modes, and a 300 GeV squark was decaying to a **top "
                   "quark** (`-3 -6`, `-5 -6`). All entries are now zeroed except "
                   "lambda''_112.\n"
                   "* With the gauginos decoupled, squarks that carry no UDD coupling have "
                   "**no open channel at all**: `DECAY 1000001` came back with width "
                   "exactly 0, i.e. a stable coloured particle. With only lambda''_112 on, "
                   "only three squark flavours have an open decay.\n\n"
                   "**Still to check before production:**\n\n"
                   "1. Re-read the decay table and confirm no squark in the `sq` "
                   "definition has zero width. If any still do, narrow the `define sq` "
                   "line in the proc_card to only the flavours lambda''_112 actually "
                   "couples to -- otherwise the sample contains stable coloured particles "
                   "and is unusable.\n"
                   "2. Confirm MET is genuinely small at reco level.\n"
                   "3. The jet spectrum is the real physics question: a two-body decay at "
                   "m_squark = {0} GeV gives jets of roughly m/2 = {1} GeV, which is "
                   "**above** the 10-30 GeV target in the specification and may reach the "
                   "HT 450 seed. This point currently produces 4 hard jets, not the "
                   "'8-12 jets of 10-30 GeV' that S5 asks for. Getting there needs an "
                   "intermediate near-degenerate state in the cascade so the visible "
                   "energy is shared among more, softer jets -- i.e. a genuinely "
                   "compressed spectrum rather than the direct 2-body decay used "
                   "here.\n").format(m, m // 2))


def other_flav(f):
    return "ee" if f == "mumu" else "mumu"


S2_HADRONIC_WARNING = """
## Measured behaviour (50-event test, PU 200, m_Zp = 500 / m_piD = 2, mumu)

Reconstructed with the repo's Delphes L1T view:

* L1T PUPPI candidates: **~6700 per event**
* Leading L1T PUPPI jet pT: median **123 GeV**, 90th percentile **213 GeV**, max **241 GeV**
* HT over PUPPI jets above 30 GeV: median **195 GeV**, 90th percentile **377 GeV**, max **470 GeV**
* L1T muons: **4.7 per event**, median pT 20.7 GeV; **78% of events have two muons
  above 2 GeV within abs(eta) < 1.5**

Measured seed fire rates (50 events each, PU 200):

| Seed | ee | mumu |
|---|---|---|
| PuppiHT 450 | 0.04 | 0.04 |
| SinglePuppiJet 230 | 0.04 | 0.02 |
| DoubleTkMuon 2,2 | 0.00 | **0.78** |
| DoubleTkMuon 4,4 | 0.00 | **0.90** |
| DoubleTkElectron 25,12 | **0.58** | 0.00 |
| PuppiETmiss 200 | 0.06 | 0.04 |

## THE ee SAMPLE IS NOT UNCOVERED AT THIS BENCHMARK POINT

`DoubleTkElectron 25,12` fires in **58%** of ee events. The premise of S2 is that
soft di-electrons have no seed below 12 GeV, but at m_Zp = 500 GeV the electrons
are not soft: median reconstructed pT is 27.8 GeV, far above the floor. **As
configured, this point does not demonstrate the gap it was designed to
demonstrate.**

Root cause: the dark meson multiplicity is too low. Only ~5-6 decaying dark
mesons share the whole event, so each carries ~50 GeV and its two leptons ~25 GeV
each.

**Lambda is not the lever.** A scan over Lambda = 0.5, 1, 2 GeV changes the dark
meson multiplicity by less than 10% (4.0 -> 5.8 mesons/event). The reason is the
specification's own `pTminFSR = 1.1 x Lambda` rule: it ties the shower cutoff to
Lambda, so lowering Lambda lowers the cutoff by the same factor and the amount of
hidden-sector radiation barely moves.

**`HiddenValley:alphaFSR` is the lever.** Decoupling the cutoff from Lambda
(`alphaOrder = 0`, fixed `alphaFSR`, `pTminFSR = 0.5`) at m_Zp = 500 GeV gives:

| alphaFSR | dark mesons | leptons | median lepton pT | DoubleTkEle 25,12 |
|---|---|---|---|---|
| (nominal, alphaOrder=1) | 5.8 | 10.9 | 5.0 GeV | 0.73 |
| 0.5 | 11.3 | 20.8 | 4.0 GeV | 0.69 |
| 0.8 | 14.3 | 25.9 | 3.4 GeV | 0.59 |
| 1.2 | 17.4 | 31.1 | 3.1 GeV | **0.49** |

Even at alphaFSR = 1.2 the fire rate is only halved, because the hard tail
survives. Lowering m_Zp is the complementary lever: at m_Zp = 200 GeV the
nominal configuration already drops to 0.36.

**Recommendation, for a decision rather than a silent change:** the cards as
shipped follow the specification (`alphaOrder = 1`, `pTminFSR = 1.1 x Lambda`,
m_Zp = 500/1000). To make the ee sample genuinely uncovered, they need
`alphaOrder = 0` with `alphaFSR` around 1 **and** a lower m_Zp (200-300 GeV).
That is a change to the specification's benchmark points, so it was not applied
unilaterally.

**Second caveat.** Because every dark meson decays to a lepton pair, the leptons
themselves cluster into PUPPI jets. At m_Zp = 500 GeV this produces ~120 GeV jets
and an HT tail reaching 470 GeV. The hadronic seeds fire at only ~4%, so this is
not currently the dominant problem, but it should be re-checked at any new
parameter point.
"""

SUEP_WARNING = """
## WARNING -- THIS IS NOT A SUEP SAMPLE

This point uses Pythia's **Hidden Valley** module as a stand-in for a SUEP
generator. It was generated this way as a deliberate, time-boxed choice; the
difference is physical, not cosmetic:

* A real SUEP is a **thermal** shower: dark hadrons are drawn from a Boltzmann
  distribution at temperature T and emitted **isotropically** in the mediator
  rest frame. That isotropy is the entire signature, and it is what makes
  structural gap 1 ("isotropic hadronic energy is untriggerable") apply.
* A Hidden Valley shower is **QCD-like**: it produces two back-to-back dark
  jets. The events are soft and high-multiplicity, but they are **not
  isotropic**.

Consequences:

* The `Lambda` parameter here is a stand-in for the dark temperature `T`. The
  mapping is **not** physical -- do not quote it as a temperature.
* The 1.6% leading-jet estimate in specification section 3 (gap 1) assumes
  uniform energy distribution and **does not apply to these events**. Expect
  more energy in the leading jet than a true SUEP would give.
* **Control C4 (anisotropy control) has been dropped by decision.** It is
  degenerate with the nominal point under this approximation and cannot be built
  from it: C4 requires a genuine isotropy knob, i.e. a real thermal shower.
  The specification flags C4 as the control "most likely to change how we
  interpret results", so if a thermal shower is ever integrated, C4 is the first
  thing to add back.

To do this properly, integrate the Knapen/Griso/Papucci thermal shower (or the
CMS-adopted equivalent) as a Pythia8 UserHook in `main_signal.cc`; the
standalone-main structure added for this campaign is the right place for it.
"""

C4_NOTE = """
## Relationship to C4

Under the Hidden Valley approximation this ISR-tagged point and the intended
anisotropy control C4 collapse into the same sample: both amount to "the same
hidden-sector event, boosted". A genuine C4 needs a thermal shower whose
isotropy can be broken independently of the production kinematics.
"""

S3_BLOCKER = """
## Blocker -- read before using this sample

Specification open item 2 asks whether the simulation chain propagates displaced
decay vertices through to the PUPPI candidates. The answer for this repo is
**partially, and not in the way this signal needs**:

* Delphes' `ParticlePropagator` does start each particle from its true
  production vertex and does compute D0/DZ, so the sample is **correct at truth
  level** and the displacement is really there.
* But the L1T reconstruction in `cards/delphes_card.dat` has **no displacement
  dependence at all**. `L1TChargedHadronTrackingEfficiency`,
  `L1TElectronTrackingEfficiency` and `L1TMuonTrackingEfficiency` are functions
  of `pt` and `eta` only -- there is no |d0| acceptance term anywhere in the
  card.
* The evasion mechanism for S3 is precisely that L1 tracking is prompt and loses
  displaced tracks. **This chain will not reproduce that**, so the sample will
  look approximately as triggerable as the ctau = 0 point rather than
  progressively less so.

Using this sample to claim "displacement defeats tkMuon" therefore requires
either an added d0-dependent efficiency term in the L1T tracking modules, or a
real CMSSW Phase-2 L1 emulation.

A second, smaller effect at long lifetime: Delphes drops particles produced
outside the tracker volume (R = 1.29 m, half-length 3.0 m). At ctau = {ctau} mm
with the boosts in this sample a fraction of the dark mesons decay beyond that
radius, and their muons are discarded entirely rather than being reconstructed
in the muon system.
"""

# Reference cross sections measured with 5-20 event Pythia runs (LO, no k-factor).
S2_XSEC = {
    (500, 2, "ee"): "5.236", (500, 2, "mumu"): "5.585",
    (500, 5, "ee"): "5.237", (500, 5, "mumu"): "4.215",
    (1000, 2, "ee"): "0.4168", (1000, 2, "mumu"): "0.3397",
    (1000, 5, "ee"): "0.4735", (1000, 5, "mumu"): "0.3879",
}
GGH_XSEC = {125: "28.07", 400: "5.212"}

# Measured on showered LHE events with anti-kT R=0.4 (Pythia SlowJet), |eta|<2.5.
RPV_MEAS = {
    (150.0, 100.0): {
        "ht": "**UNRESOLVED** -- 0.00 and 0.27 in two samples, see below",
        "jet": "no (leading jet 68-99 GeV, both samples)",
        "text": ("Two independent runs at this mass point, anti-kT R=0.4, |eta| < 2.5.\n"
                 "They **disagree**, and both are fluctuation-dominated:\n\n"
                 "| quantity | run A (7 ev) | run B (11 ev) |\n"
                 "|---|---|---|\n"
                 "| N(jets > 10 GeV) | 9.3 | 7.6 |\n"
                 "| N(jets > 30 GeV) | 4.3 | 4.3 |\n"
                 "| HT30 median | 231 GeV | 284 GeV |\n"
                 "| leading jet median | 68 GeV | 99 GeV |\n"
                 "| MET median | 0 | 0 |\n"
                 "| fires PuppiHT450 | 0.00 | **0.27** |\n"
                 "| fires SinglePuppiJet230 | 0.00 | 0.00 |\n\n"
                 "**What is established:** the topology gives roughly 8 jets above 10 GeV "
                 "(both runs land at 7.6-9.3, in or next to the specified 8-12 band), the "
                 "leading jet stays well under the 230 GeV seed, and MET is identically "
                 "zero. This is the best of the four points scanned and the recommended "
                 "one.\n\n"
                 "**What is NOT established:** whether it clears PuppiHT 450. The two "
                 "runs give 0.00 and 0.27. With ~10 events each neither is meaningful, and "
                 "an HT30 median of 231-284 GeV sits close enough to 450 that the tail "
                 "matters. **Resolve this before using the point in any sensitivity "
                 "claim** -- and if the HT rate is real, drop m_squark further, since "
                 "HT_true = 2 x m_squark scales directly with it."),
    },
    (120.0, 90.0): {
        "ht": "no (HT30 median 356 GeV, 4 events)",
        "jet": "no (leading jet median 165 GeV, 4 events)",
        "text": ("Shape measured on **only 4 unweighted events** -- indicative at best:\n\n"
                 "* N(jets > 10 GeV) = 7.5, N(jets > 30 GeV) = 3.5\n"
                 "* HT30 median 356 GeV, leading jet median 165 GeV, MET median 0\n\n"
                 "Below the 8-jet target. Prefer `RPV_squark150_cascade_LSP100`."),
    },
}

HAA_NOTES = {
    "4tau": ("\n## Note\n\nThe leptonic tau decays give a few soft electrons and "
             "muons. The muonic ones can occasionally reach the BPH DoubleTkMuon "
             "2,2 seed, so this point is not a *pure* trigger-blind sample; "
             "quantify the leakage before using it in a sensitivity claim.\n"),
    "4b": ("\n## Note\n\nm_a must clear 2 m_b ~ 9.4 GeV for this mode, which is why "
           "the mass points start at 15 GeV rather than the 5 GeV used for the tau "
           "mode. The four b jets are soft and, at the lower masses, the two b jets "
           "from one `a` merge into a single reconstructed jet.\n"),
    "4gamma": ("\n## Note -- collimation depends strongly on m_a\n\n"
               "All three mass points give exactly 4.0 signal photons per event with a "
               "median pT around 21-24 GeV, but how they reconstruct differs:\n\n"
               "| m_a | median dR(gamma gamma) | fraction with dR < 0.04 |\n"
               "|---|---|---|\n"
               "| 1 GeV | 0.047 | **0.38** |\n"
               "| 5 GeV | 0.247 | 0.00 |\n"
               "| 10 GeV | 0.506 | 0.00 |\n\n"
               "At m_a = 1 GeV the pair is strongly collimated and a large fraction "
               "merges into a **single** EM cluster -- the 'photon jet' signature -- "
               "so do not interpret that point as four resolved photons. At 5 and "
               "10 GeV the photons are well separated.\n\n"
               "Note also that the median photon pT sits close to the "
               "DoubleTkIsoPhoton 22,12 threshold, so this sample is not automatically "
               "below the photon seed; check it at reconstruction level.\n"),
}

HAA_DISPLACED_NOTE = """
## Displacement -- verified, and how it is imposed

The lifetime is imposed through the **width**, not through `36:tau0`.
Particle 36 is a resonance with `doForceWidth` on, so Pythia derives
tau0 = hbar / Gamma at initialisation and silently overwrites any tau0 set by
hand. Setting `36:tau0` alone produces a sample that is prompt despite asking for
a displacement -- this was observed directly before it was fixed. The width is
therefore set to Gamma = hbar*c / ctau = 1.973e-13 / ctau[mm], and tau0 is set as
well so the two agree.

`ParticleDecays:limitTau0 = off` is also required, or Pythia refuses to decay
anything with tau0 above its default 10 mm ceiling and the pseudoscalar becomes
silently invisible.

Measured transverse decay radius (150 events), confirming the scaling:

| point | median Rxy | outside tracker |
|---|---|---|
| `hToAA_4tau_ma10_ctau1mm` | 1.7 mm | 0% |
| `hToAA_4tau_ma10_ctau10mm` | 17.0 mm | 0% |
| `hToAA_4tau_ma10_ctau100mm` | 169.8 mm | 6% |
| `hToAA_4b_ma30_ctau10mm` | 5.9 mm | 0% |
| `hToAA_4b_ma30_ctau100mm` | 58.7 mm | 1% |

The median radius exceeds ctau because of the boost, and a lighter `a` is boosted
more -- which is why the 4tau points (m_a = 10) displace further than the 4b
points (m_a = 30) at the same lifetime.

## Downstream limits

* `cards/delphes_card.dat` has **no d0 dependence** in its L1T tracking
  efficiencies -- they are functions of pt and eta only. The sample is correct at
  truth level, but the chain will not reproduce the loss of displaced tracks at
  L1.
* Delphes drops particles produced outside the tracker (R = 1.29 m,
  half-length 3 m). That costs nothing at ctau = 1 and 10 mm and only a few
  percent at 100 mm, as tabulated above, but it grows quickly at longer
  lifetimes.
"""

RPV_EWKINO_DISP_NOTES = """
## Why this point is long-lived by construction

Below about 180 GeV the lambda''_323 mode `n1 -> t s b` closes, because the top
cannot be on shell. The operator that stays open is lambda''_223 (c s b), and it
runs off the **charm** Yukawa rather than the top Yukawa -- smaller by roughly
(y_c/y_t)^2 ~ 1e-5. The Higgsino is therefore naturally long-lived: the
displacement is a consequence of the mass being below the top threshold, not
something imposed by hand.

The width is nonetheless set explicitly to hit ctau = {c:g} mm, so the lifetime
is a controlled knob rather than an accident of the coupling value.

## How the displacement survives the chain -- CHECK THIS FIRST

The decays are generated in the matrix element, so by default the daughters
would be written at the primary vertex and **all the displacement would be
lost**. Two things prevent that:

* the run card sets `time_of_flight = 0`, so MG5 writes the invariant lifetime
  (`VTIMUP`) of the intermediate resonance into the LHE, and
* the Higgsino width is set to the target ctau.

Pythia then propagates the resonance before decaying it, and Delphes'
`ParticlePropagator` starts the daughters from the displaced vertex.

**This is the step most likely to fail silently.** Before trusting the sample,
open the LHE and confirm `VTIMUP` is non-zero for the 1000022 entries. If it is
zero, the sample is prompt and worthless as a displaced benchmark.

## Downstream caveats, same as S3

* `cards/delphes_card.dat` has **no d0 dependence** in its L1T tracking
  efficiencies -- they are functions of pt and eta only. So this sample is
  correct at truth level but the chain will not reproduce the loss of displaced
  tracks at L1. See the S3 point READMEs for the same limitation.
* Delphes drops particles produced outside the tracker (R = 1.29 m). At
  ctau = {c:g} mm with the boosts here that should be a small effect, but it grows
  quickly if the lifetime is scanned upward.

## Measured -- and the displacement is confirmed real

MG5 generates the process and the lifetime survives into the LHE. Over 4000
resonance entries:

| VTIMUP | measured | expected for ctau = {c:g} mm |
|---|---|---|
| mean | **10.02 mm** | 10.0 |
| median | **6.84 mm** | 6.93 (= 10 ln2) |
| max | 90.5 mm | — |

That is a textbook exponential at the requested lifetime, so the
`time_of_flight = 0` mechanism works and the sample really is displaced.

Jets, on 500 showered events (anti-kT R = 0.4, |eta| < 2.5):

| quantity | value |
|---|---|
| N(jets > 10 GeV) | **6.4** |
| N(jets > 30 GeV) | 3.8 |
| HT over jets > 30 GeV, median | **238 GeV** |
| leading jet, median | 89 GeV |
| MET, median | 6 GeV |
| fires PuppiHT450 | **0.11** |
| fires SinglePuppiJet230 | **0.04** |

**Unweighting is excellent: the full 2000-event request came back unweighted.**
Compare the squark cascade's eight-parton chain at 0.2-0.7%. This point is cheap
to produce at scale.

## This is the better of the two Higgsino points for menu evasion

It fires PuppiHT450 in 11% and SinglePuppiJet230 in 4%, against 32% and 16% for
the prompt `RPV_ewkino200_UDD`. Being below the top threshold is what does it --
no hadronic top means no hard jets -- and the same fact is what makes it
long-lived. The cost is jet multiplicity: 6.4 rather than 7.1, both short of the
8-12 target.

## Downstream caveats, same as S3

* `cards/delphes_card.dat` has **no d0 dependence** in its L1T tracking
  efficiencies -- they are functions of pt and eta only. The sample is correct at
  truth level, but the chain will not reproduce the loss of displaced tracks at
  L1. See the S3 point READMEs for the identical limitation.
* Delphes drops particles produced outside the tracker (R = 1.29 m). The measured
  VTIMUP tail reaches 90 mm proper, so with boost this is a small but non-zero
  effect here, and it grows quickly if the lifetime is scanned upward.
"""

RPV_EWKINO_NOTES = """
## Why this point exists

`RPV_squark150_cascade_LSP100` reproduces the S5 signature but a 150 GeV squark
is excluded by existing LHC searches. This point is the non-excluded companion:

* **Production is electroweak**, so the cross section is O(pb) rather than the
  ~1600 pb of 150 GeV squarks. The RPV multijet searches that exclude light
  squarks are driven by strong production and have very little reach here.
* The binding constraint is LEP, m_chargino >~ 92-103 GeV. A {m:g} GeV Higgsino
  is comfortably allowed.

## Why heavy flavour is essential here

A Higgsino couples to a quark and a squark through **that quark's Yukawa**. With
lambda''_112 (u d s) the coupling is Yukawa-suppressed to the point where the
decay is not prompt, so a pure-Higgsino benchmark with light-flavour decays does
not work. lambda''_323 (t s b) goes through the **top** Yukawa instead, which is
large: the decay is prompt and unsuppressed.

Allowing heavy flavour therefore does two things at once -- it makes a genuine
pure-Higgsino benchmark possible at all, and it raises the jet multiplicity from
6 to 8-10, because `n1 -> t s b` with a hadronic top is five jets rather than
three.

## Mass choice

The top must be on shell for this to be prompt. Below about 180 GeV the t s b
mode closes, the decay becomes four-body through an off-shell top, and the
Higgsino becomes **long-lived** -- a displaced multijet signature. That is a
legitimate and arguably more interesting signal for this analysis (it overlaps
with the S3 displacement theme), but it is a different sample and is not mixed
in here. If you want it, lower the mass below ~180 GeV or reduce lambda''_323,
and check the resulting ctau before trusting the sample.

## Measured

MG5 generates the process cleanly (62 subprocesses) and finds the predicted
modes `n1 > s t b` and `x1+ > s~ b~ b~`. Measured on 500 showered events,
anti-kT R = 0.4, |eta| < 2.5:

| quantity | value |
|---|---|
| N(jets > 10 GeV) | **7.1** |
| N(jets > 30 GeV) | 4.7 |
| HT over jets > 30 GeV, median | **355 GeV** |
| leading jet, median | 122 GeV |
| MET, median | 8 GeV |
| fires PuppiHT450 | **0.32** |
| fires SinglePuppiJet230 | **0.16** |

Unweighting is comfortable -- 530 events from a 2000 request, far better than the
squark cascade's 0.2-0.7%.

## This point leaks into the menu -- read before using it

**It fires PuppiHT450 in 32% of events and SinglePuppiJet230 in 16%.** The
hadronic top that buys the jet multiplicity also supplies hard jets, and
HT_true = 2m = 400 GeV sits close enough to the 450 seed that a third of the
distribution crosses it. As a demonstration that the menu is *blind* to this
topology, this point is weak.

The measured multiplicity is also **7.1 jets, not the 8-10 the arithmetic
suggested** -- jets merge and some fall below 10 GeV.

Both problems get worse at m = 300 (HT_true = 600 GeV). The mass cannot be
lowered either, because below ~180 GeV the top goes off shell and the decay stops
being prompt.

**If the goal is menu evasion rather than raw multiplicity, prefer
`RPV_ewkino150_UDD_ctau10mm`**: it sits below the top threshold, fires HT450 in
only 11% and SinglePuppiJet230 in 4%, and carries a displaced vertex as well.
This point is better used as the *prompt* reference against which that one is
compared.
"""

RPV_CASCADE_NOTES = """
## Why the decays are in the matrix element

Two independent blockers rule out the ordinary decay-table route for a light RPV
LSP, both found by running this chain:

1. **MG5 `compute_widths` zeroes any partial width below the QCD scale**
   (~0.2 GeV). The compressed cascade widths are 0.01-0.03 GeV -- physically
   prompt, but written out as exactly `0.000000e+00`. The squarks and the LSP
   then come back **stable**, and the events are useless. A light RPV LSP
   decaying through lambda'' = 1e-2 is far below the threshold and can never be
   described this way.
2. **Letting Pythia recompute the widths instead** (`SLHA:useDecayTable = off`)
   fails differently: Pythia's RPV machinery emits invalid particle codes on
   this UFO's SLHA (`unknown particle code, id = -2000304`) and every event is
   rejected.

Generating the cascade in the matrix element sidesteps both -- the LHE arrives
fully decayed and no decay table is ever consulted.

## The mass points are forced by physics, not preference

RPV has no invisible particle, so the entire parent mass becomes visible jets:
HT_true = 2 x m_squark. For N jets of average energy E that fixes
2 x m_squark = N x E. Ten jets at 20-30 GeV therefore requires
m_squark ~ 100-150 GeV. **The specification's 300 and 600 GeV cannot produce
10-30 GeV jets under any topology** -- at 300 GeV the same cascade gives eight
jets averaging ~75 GeV. Both are generated so the contrast is visible, but only
the light points meet the stated target.

Note that squarks at 120-150 GeV are excluded by existing LHC searches. For an
anomaly-detection benchmark that is acceptable -- what matters is the signature,
not the exclusion status -- but it must not be presented as a viable model point.

## Measured behaviour

{meas}

## Unweighting efficiency warning

The eight-parton decay chain unweights poorly: a 1000-event request returned
**7** unweighted events with the near-zero widths MG5 needs for the propagator.
Raising the Breit-Wigner widths (squark 1.5 GeV, LSP 0.1 GeV) improves this
substantially and is what the shipped customizecards use, but **measure the
per-job yield before sizing a 100k-event production** -- this point is far more
expensive per event than any other in the campaign.
"""


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="processes")
    args = ap.parse_args()

    written = []

    for name, body in (s2_points() + s3_points() + s1_points()
                       + s4_points() + c3_points()):
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        path = os.path.join(d, "{0}_pythia_card.dat".format(name))
        with open(path, "w") as fh:
            fh.write(body)
        written.append(path)

    for name, m in rpv_points():
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "{0}_proc_card.dat".format(name)), "w") as fh:
            fh.write(RPV_PROC_CARD)
        with open(os.path.join(d, "{0}_run_card.dat".format(name)), "w") as fh:
            fh.write(rpv_run_card())
        with open(os.path.join(d, "{0}_customizecards.dat".format(name)), "w") as fh:
            fh.write(rpv_customize(m))
        written.append(d)

    for m, y in rpv_cascade_points():
        name = "RPV_squark{0:g}_cascade_LSP{1:g}".format(m, y)
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "{0}_proc_card.dat".format(name)), "w") as fh:
            fh.write(RPV_CASCADE_PROC_CARD)
        with open(os.path.join(d, "{0}_run_card.dat".format(name)), "w") as fh:
            fh.write(rpv_run_card())
        with open(os.path.join(d, "{0}_customizecards.dat".format(name)), "w") as fh:
            fh.write(rpv_cascade_customize(m, y))
        _unused_cascade_readme_marker = None
        write_readme(
            os.path.join(d, "README.md"),
            name=name, sid="S5 (stealth SUSY / light RPV cascade)", mode="madgraph",
            what=("Pair production of {0:g} GeV right-handed up squarks, each decaying to a "
                  "quark plus a {1:g} GeV neutralino LSP, with the LSP decaying to three "
                  "light quarks through the lambda''_112 UDD operator. Eight partons at "
                  "the hard-process level, no MET, no isotropy -- the 'high multiplicity "
                  "but not isotropic' corner.").format(m, y),
            config=("* Model `RPVMSSM_UFO`; the full cascade is in the **matrix element**, "
                    "not in decay tables (see below)\n"
                    "* m_squark = {0:g} GeV, m_LSP = {1:g} GeV, splitting {2:g} GeV\n"
                    "* Only lambda''_112 is switched on, so the decays are to light quarks\n"
                    "* Gluino, third generation and the heavier gauginos decoupled at "
                    "{3:g} GeV\n"
                    "* run_card deviates from the repo convention (`ickkw = 0`, "
                    "`xqcut = 0`, `ptj1min = 0`) per specification section 4").format(
                        m, y, m - y, m + 400.0),
            menu=MENU.format(ht=RPV_MEAS.get((m, y), {}).get("ht", "to measure"),
                             jet=RPV_MEAS.get((m, y), {}).get("jet", "to measure"),
                             quad="to measure", bph="no", mu44="no", ele="no",
                             pho="no", tau="no", met="**no** -- RPV, nothing escapes"),
            notes=RPV_CASCADE_NOTES.format(
                m=m, y=y, meas=RPV_MEAS.get((m, y), {}).get("text",
                    "Not yet measured for this point; run the scan in "
                    "`make_signal_cards.py` docs to fill this in.")))
        written.append(d)

    for m in rpv_ewkino_points():
        name = "RPV_ewkino{0:g}_UDD".format(m)
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "{0}_proc_card.dat".format(name)), "w") as fh:
            fh.write(RPV_EWKINO_PROC_CARD)
        with open(os.path.join(d, "{0}_run_card.dat".format(name)), "w") as fh:
            fh.write(rpv_run_card())
        with open(os.path.join(d, "{0}_customizecards.dat".format(name)), "w") as fh:
            fh.write(rpv_ewkino_customize(m))
        write_readme(
            os.path.join(d, "README.md"),
            name=name, sid="S5b (light RPV Higgsinos -- non-excluded companion)",
            mode="madgraph",
            what=("Electroweak production of a near-degenerate Higgsino multiplet at "
                  "{0:g} GeV, each state decaying through the lambda''_323 UDD operator to "
                  "t s b. With a hadronic top that is five jets per neutralino, so the "
                  "pair gives **8-10 jets**, several of them b-tagged, with no MET.\n\n"
                  "This is the **non-excluded companion** to "
                  "`RPV_squark150_cascade_LSP100`. That point reproduces the target "
                  "signature but sits at a squark mass ruled out by existing LHC searches; "
                  "this one delivers a comparable topology at a mass that is not.").format(m),
            config=("* Model `RPVMSSM_UFO`; electroweakino decays in the **matrix "
                    "element**, not decay tables (same reason as the squark cascade)\n"
                    "* Production: `p p > n1 x1+`, `n1 x1-`, `x1+ x1-` -- electroweak\n"
                    "* Multiplet at {0:g} GeV, everything else decoupled at 1 TeV\n"
                    "* **lambda''_323 only** (t s b); every other RVLAMUDD entry zeroed, "
                    "since the UFO ships 0.2 on all of them\n"
                    "* The top is left undecayed in the matrix element and handed to "
                    "Pythia -- its width is large and standard\n"
                    "* Expected: 8-10 jets, HT_true = 2m = {1:.0f} GeV\n"
                    "* Cross section: **do not use the number MG5 reports** -- the widths "
                    "are hand-set, see the squark cascade README. Normalise with the "
                    "production cross section generated on its own.").format(m, 2 * m),
            menu=MENU.format(
                ht=("**verify** -- HT_true = {0:.0f} GeV, close to the 450 seed".format(2 * m)
                    if m >= 250 else
                    "**likely no** -- HT_true = {0:.0f} GeV spread over 8-10 jets".format(2 * m)),
                jet="**no** (expected leading jet well under 230)",
                quad="verify", bph="no", mu44="no", ele="no", pho="no", tau="no",
                met=("mostly **no** -- RPV, nothing escapes; small residual MET from "
                     "semileptonic top decays")),
            notes=RPV_EWKINO_NOTES.format(m=m))
        written.append(d)

    for m, ctau in rpv_ewkino_disp_points():
        name = "RPV_ewkino{0:g}_UDD_ctau{1:g}mm".format(m, ctau)
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "{0}_proc_card.dat".format(name)), "w") as fh:
            fh.write(RPV_EWKINO_DISP_PROC_CARD)
        # time_of_flight = 0 so MG5 writes the resonance lifetime into the LHE.
        with open(os.path.join(d, "{0}_run_card.dat".format(name)), "w") as fh:
            fh.write(rpv_run_card(time_of_flight="0.0"))
        with open(os.path.join(d, "{0}_customizecards.dat".format(name)), "w") as fh:
            fh.write(rpv_ewkino_disp_customize(m, ctau))
        write_readme(
            os.path.join(d, "README.md"),
            name=name, sid="S5c (displaced RPV Higgsino, below the top threshold)",
            mode="madgraph",
            what=("Electroweak production of a near-degenerate Higgsino multiplet at "
                  "{0:g} GeV -- **below the top threshold** -- decaying through "
                  "lambda''_223 to c s b with a proper lifetime of **ctau = {1:g} mm**. "
                  "Three jets per state, two of them heavy flavour, all emerging from a "
                  "displaced vertex. No MET.\n\n"
                  "This is the long-lived member of the S5b family: the same "
                  "non-excluded electroweak production, but with the decay pushed "
                  "off-vertex rather than prompt.").format(m, ctau),
            config=("* Model `RPVMSSM_UFO`; decays in the **matrix element**\n"
                    "* Production: `p p > n1 x1+`, `n1 x1-`, `x1+ x1-` -- electroweak\n"
                    "* Multiplet at {0:g} GeV, everything else decoupled at 1 TeV\n"
                    "* **lambda''_223 only** (c s b); all other RVLAMUDD entries zeroed\n"
                    "* Width set to {1:.4e} GeV, i.e. ctau = {2:g} mm via "
                    "ctau[mm] = 1.973e-13 / Gamma[GeV]\n"
                    "* **run_card sets `time_of_flight = 0`** so MG5 writes the resonance "
                    "lifetime (VTIMUP) into the LHE -- without this the displacement is "
                    "silently lost\n"
                    "* To scan the lifetime, change only the `1000022` width in the "
                    "customizecards; the process directory does not need "
                    "regenerating").format(m, CTAU_MM_TO_WIDTH / ctau, ctau),
            menu=MENU.format(
                ht="**likely no** -- HT_true = {0:.0f} GeV over six jets".format(2 * m),
                jet="**no**", quad="verify", bph="no", mu44="no", ele="no",
                pho="no", tau="no", met="**no** -- RPV, nothing escapes"),
            notes=RPV_EWKINO_DISP_NOTES.format(m=m, c=ctau))
        written.append(d)

    build_readmes(args.outdir)

    print("wrote {0} process definitions".format(len(written)))
    for w in written:
        print("  " + w)


if __name__ == "__main__":
    main()
