#!/usr/bin/env python3
"""
make_signal_cards.py

Generates the AIDA-Scout signal and control process directories under
processes/.  Everything it writes is a plain card of the kind the repo already
uses, so the generated points are ordinary processes as far as run.sh,
write_jobs.py and submit_to_condor.py are concerned.  The script exists so the
parameter scans stay reproducible: re-running it regenerates every point.

    python3 make_signal_cards.py [--outdir processes]

Two card flavours are produced:

  *_pythia_card.dat   Pythia8-only generation (Hidden Valley dark showers,
                      Higgs portal, Z').  Consumed by main_signal.cc via the
                      'pythia' branch of run.sh.  NEVENTS / NSEED are
                      placeholders, matching processes/minbias.

  *_proc_card.dat + *_run_card.dat + *_param_card.dat
                      MadGraph hard process (RPV MSSM), consumed by the
                      existing 'madgraph' branch of run.sh.

See processes/README_AIDA_Scout.md for the physics rationale per point.
"""

import argparse
import os

# ---------------------------------------------------------------------------
# Shared header.  Beam energy and tune come from main_signal.cc; anything set
# here overrides those defaults.
# ---------------------------------------------------------------------------

HEADER = """! ---------------------------------------------------------------------------
! {title}
!
! {subtitle}
!
! Generated by make_signal_cards.py -- edit that script, not this file.
! ---------------------------------------------------------------------------

Beams:idA = 2212
Beams:idB = 2212
Beams:eCM = 14000.

Random:setSeed = on
Random:seed = NSEED
Main:numberOfEvents = NEVENTS

! No generator-level cuts of any kind are applied: these signals live entirely
! below the thresholds that a default cut set would impose (spec section 4).

Init:showChangedSettings = on
Init:showChangedParticleData = on
Next:numberCount = 500
Next:numberShowInfo = 0
Next:numberShowProcess = 1
Next:numberShowEvent = 0
"""


def hv_block(lam, ngauge=3, nflav=2, prob_vector=0.75):
    """Hidden Valley shower + hadronisation settings (spec section S2)."""
    return """
! ---- Hidden Valley shower and hadronisation ----
HiddenValley:fragment   = on
HiddenValley:FSR        = on
HiddenValley:alphaOrder = 1
HiddenValley:Ngauge     = {ngauge}
HiddenValley:nFlav      = {nflav}
HiddenValley:Lambda     = {lam:g}
HiddenValley:pTminFSR   = {ptmin:g}
HiddenValley:probVector = {pv:g}
""".format(ngauge=ngauge, nflav=nflav, lam=lam, ptmin=1.1 * lam, pv=prob_vector)


def hv_spectrum(m_pi, m_qv=None, m_rho=None):
    """
    Dark meson spectrum.

    With nFlav = 2 the hidden sector contains three pseudoscalars (4900111
    piv11, 4900211 piv21, 4900221 piv22) and three vectors (4900113, 4900213,
    4900223).  The off-diagonal 4900211 / 4900213 carry a conserved dark flavour
    and have *empty* decay tables in Pythia's ParticleData -- they are the
    stable dark-matter states.  We set their masses so the spectrum is
    degenerate, and mark them explicitly stable rather than relying on the empty
    table.
    """
    if m_qv is None:
        m_qv = m_pi          # constituent mass, m_rhov ~ 2 m_qv
    if m_rho is None:
        m_rho = 2.0 * m_pi
    return """
! ---- Dark sector spectrum ----
4900101:m0 = {mqv:g}       ! qv1
4900102:m0 = {mqv:g}       ! qv2
4900111:m0 = {mpi:g}       ! piv11 (diagonal, decays)
4900211:m0 = {mpi:g}       ! piv21 (off-diagonal, stable)
4900221:m0 = {mpi:g}       ! piv22 (diagonal, decays)
4900113:m0 = {mrho:g}      ! rhov11 (diagonal, decays)
4900213:m0 = {mrho:g}      ! rhov21 (off-diagonal, stable)
4900223:m0 = {mrho:g}      ! rhov22 (diagonal, decays)

! The off-diagonal (dark-flavoured) states are stable and invisible.  This is
! identical between the ee and mumu samples, so the controlled comparison is
! unaffected, but it does mean a sizeable fraction of the dark shower energy
! never returns to the SM.
4900211:mayDecay = off
4900213:mayDecay = off
""".format(mqv=m_qv, mpi=m_pi, mrho=m_rho)


def hv_decays(products, comment, tau0_mm=None):
    """
    Force every *decaying* dark meson into the same final state.

    The spec fragment only pins 4900111.  With probVector = 0.75 three quarters
    of the dark mesons are vectors, so leaving 4900113 / 4900223 on their
    default flavour-democratic tables would leave most of the visible energy
    flavour-mixed and destroy the ee vs mumu contrast.  Both the pseudoscalars
    and the vectors are therefore forced to the same channel.  meMode 91 is what
    Pythia's own piv table uses.
    """
    ids = [4900111, 4900221, 4900113, 4900223]
    lines = ["\n! ---- Dark meson decays: {0} ----".format(comment)]
    for pid in ids:
        lines.append("{0}:oneChannel = 1 1.0 91 {1}".format(pid, products))
    if tau0_mm is not None:
        lines.append("\n! ---- Proper lifetime, ctau = {0:g} mm ----".format(tau0_mm))
        lines.append("ParticleDecays:limitTau0 = off")
        for pid in ids:
            lines.append("{0}:tau0 = {1:g}".format(pid, tau0_mm))
    return "\n".join(lines) + "\n"


def zv_block(mzp):
    """q qbar -> Zv -> qv qvbar.  No UFO needed; Pythia has this natively."""
    return """
! ---- Hard process: q qbar -> Zv -> qv qvbar ----
! Pythia's native Hidden Valley Z' resonance (4900023).  This replaces the
! MadGraph 'generate p p > zp, zp > qv qv~' step in the spec: the HV module
! already implements it with exactly the 4900xxx conventions the shower expects,
! so no external Hidden Valley UFO is involved and there is no risk of an
! ID-convention mismatch between the hard process and the shower.
HiddenValley:ffbar2Zv = on
4900023:m0     = {m:g}
4900023:mWidth = {w:g}
4900023:mMin   = {mmin:g}
4900023:mMax   = {mmax:g}

! Decay only into the hidden sector (first nFlav dark quark flavours).
4900023:onMode = off
4900023:onIfMatch = 4900101 -4900101
4900023:onIfMatch = 4900102 -4900102
""".format(m=mzp, w=0.01 * mzp, mmin=0.8 * mzp, mmax=1.2 * mzp)


def higgs_portal_block(m_phi, isr_pthat=None):
    """gg -> phi (loop induced) with phi -> qv qvbar, i.e. a Higgs portal."""
    if isr_pthat is None:
        proc = """HiggsSM:gg2H = on"""
        note = """! Inclusive gg -> phi production, NO ISR requirement.  This is deliberate:
! tagging an ISR jet is exactly the trigger handle this analysis is trying to
! avoid needing (spec S1, 'Critical')."""
    else:
        proc = """HiggsSM:gg2Hg(l:t) = on
HiggsSM:qg2Hq(l:t) = on
HiggsSM:qqbar2Hg(l:t) = on
PhaseSpace:pTHatMin = {0:g}""".format(isr_pthat)
        note = """! phi + jet production with a hard recoil jet -- the ISR-tagged control (C1).
! This SHOULD fire the existing HT / single-jet seeds."""
    return """
! ---- Hard process: gg -> phi, phi -> qv qvbar (Higgs portal) ----
{note}
{proc}

25:m0     = {m:g}
25:mMin   = {mmin:g}
25:mMax   = {mmax:g}

! The portal channel is ADDED, not substituted.  gg -> phi production is a
! resonance process whose cross section Pythia builds from the dynamically
! computed phi -> g g partial width, so replacing the whole decay table with
! 'oneChannel' drives Gamma(phi->gg) -- and hence the cross section -- to zero
! ("all processes have vanishing cross sections").  Adding the channel keeps
! the SM table alive for production, and onMode/onIfMatch then leaves only the
! portal open for the decay.  meMode 102 mirrors Pythia's own Zv -> qv qvbar.
25:addChannel = 1 1.0 102 4900101 -4900101
25:onMode = off
25:onIfMatch = 4900101 -4900101
""".format(note=note, proc=proc, m=m_phi,
           mmin=0.5 * m_phi, mmax=1.5 * m_phi)


# ---------------------------------------------------------------------------
# Point definitions
# ---------------------------------------------------------------------------

LEPTON = {
    "ee":   ("11 -11", "100% -> e+ e-"),
    "mumu": ("13 -13", "100% -> mu+ mu-"),
}


def s2_points():
    """S2: dark shower -> soft dileptons, matched ee / mumu pairs."""
    out = []
    for mzp in (500, 1000):
        for mpi in (2, 5):
            for flav in ("ee", "mumu"):
                name = "HVdilep_Zp{0}_piD{1}_{2}".format(mzp, mpi, flav)
                products, comment = LEPTON[flav]
                body = (
                    HEADER.format(
                        title="S2 -- Hidden Valley dark shower to soft dileptons ({0})".format(flav),
                        subtitle="m_Zp = {0} GeV, m_piD = {1} GeV, Lambda = {1} GeV".format(mzp, mpi))
                    + zv_block(mzp)
                    + hv_block(lam=float(mpi))
                    + hv_spectrum(float(mpi))
                    + hv_decays(products, comment)
                )
                out.append((name, body))
    return out


def s3_points():
    """S3: displaced soft dimuons -- the S2 mumu chain with a lifetime scan."""
    out = []
    mzp, mpi = 500, 2
    products, comment = LEPTON["mumu"]
    for ctau in (1, 10, 100):
        name = "HVdilep_Zp{0}_piD{1}_mumu_ctau{2}mm".format(mzp, mpi, ctau)
        body = (
            HEADER.format(
                title="S3 -- Displaced soft dimuons, ctau = {0} mm".format(ctau),
                subtitle="Identical to HVdilep_Zp{0}_piD{1}_mumu except for the dark meson proper lifetime".format(mzp, mpi))
            + zv_block(mzp)
            + hv_block(lam=float(mpi))
            + hv_spectrum(float(mpi))
            + hv_decays(products, comment, tau0_mm=float(ctau))
        )
        out.append((name, body))
    return out


def s1_points():
    """S1 approximation: soft high-multiplicity hadronic via a Higgs portal."""
    out = []
    # Dark mesons -> light SM hadrons.  m_X = 2 GeV cannot reach b bbar, so the
    # default (b-dominated) piv table is replaced by light quarks.
    had = ("\n! ---- Dark meson decays: generic hadronic (light quarks) ----\n"
           "4900111:oneChannel = 1 1.0 91 3 -3\n"
           "4900221:oneChannel = 1 1.0 91 3 -3\n"
           "4900113:oneChannel = 1 0.34 91 1 -1\n"
           "4900113:addChannel = 1 0.33 91 2 -2\n"
           "4900113:addChannel = 1 0.33 91 3 -3\n"
           "4900223:oneChannel = 1 0.34 91 1 -1\n"
           "4900223:addChannel = 1 0.33 91 2 -2\n"
           "4900223:addChannel = 1 0.33 91 3 -3\n")

    for m_phi, lam in ((125, 1.0), (125, 2.0), (400, 2.0), (400, 4.0)):
        name = "SUEPlike_HV_mPhi{0}_mX2_Lam{1:g}".format(m_phi, lam)
        body = (
            HEADER.format(
                title="S1 (APPROXIMATION) -- soft high-multiplicity hadronic, Higgs portal",
                subtitle="m_phi = {0} GeV, m_X = 2 GeV, Lambda = {1:g} GeV -- NOT a thermal SUEP shower, see README".format(m_phi, lam))
            + higgs_portal_block(float(m_phi))
            + hv_block(lam=lam)
            + hv_spectrum(2.0)
            + had
        )
        out.append((name, body))

    # C1: the same model with a hard ISR jet required.
    name = "SUEPlike_HV_mPhi125_mX2_Lam2_ISR"
    body = (
        HEADER.format(
            title="C1 (CONTROL) -- ISR-tagged soft high-multiplicity hadronic",
            subtitle="m_phi = 125 GeV, m_X = 2 GeV, Lambda = 2 GeV, pThat > 150 GeV recoil jet")
        + higgs_portal_block(125.0, isr_pthat=150.0)
        + hv_block(lam=2.0)
        + hv_spectrum(2.0)
        + had
    )
    out.append((name, body))
    return out


def s4_points():
    """S4: h -> a a -> 4 tau."""
    out = []
    for ma in (5, 10, 15):
        name = "hToAA_4tau_ma{0}".format(ma)
        body = (
            HEADER.format(
                title="S4 -- h -> a a -> 4 tau",
                subtitle="m_h = 125 GeV, m_a = {0} GeV, a -> tau+ tau- at 100%".format(ma))
            + """
! ---- Hard process: gg -> h, h -> a a, a -> tau tau ----
! Handled entirely in Pythia's decay tables, so no 2HDM+S UFO is needed.
! meMode 100 is required: both 25 and 36 are resonances, and for a resonance a
! branching ratio cannot be overridden without meMode >= 100.
!
! Both exotic channels are ADDED rather than substituted: gg -> h production is
! built from the dynamically computed h -> g g partial width, and 'oneChannel'
! would zero it out along with the rest of the SM table, aborting the run with
! "all processes have vanishing cross sections".
HiggsSM:gg2H = on

25:m0     = 125.0
25:mMin   = 100.0
25:mMax   = 150.0
25:addChannel = 1 1.0 100 36 36
25:onMode = off
25:onIfMatch = 36 36

36:m0     = {ma:g}
36:mWidth = 0.001
36:mMin   = {mmin:g}
36:mMax   = {mmax:g}
36:doForceWidth = on
36:tau0   = 0.
36:addChannel = 1 1.0 100 15 -15
36:onMode = off
36:onIfMatch = 15 -15
""".format(ma=float(ma), mmin=0.5 * ma, mmax=1.5 * ma)
        )
        out.append((name, body))
    return out


def c3_points():
    """C3: low-mass dijet resonance that the existing seeds already cover."""
    name = "Zprime_qq_m500"
    body = (
        HEADER.format(
            title="C3 (CONTROL) -- low-mass dijet resonance",
            subtitle="Sequential Z' at 500 GeV decaying to light quarks; two ~250 GeV jets")
        + """
! ---- Hard process: q qbar -> Z' -> q qbar ----
! Two ~250 GeV jets clear both SinglePuppiJet 230 and PuppiHT 450 comfortably.
! This is the 'AD should not claim credit here' control.
NewGaugeBoson:ffbar2gmZZprime = on
Zprime:gmZmode = 3

32:m0     = 500.0
32:mWidth = 5.0
32:mMin   = 400.0
32:mMax   = 600.0

32:onMode = off
32:onIfAny = 1 2 3 4 5
"""
    )
    return [(name, body)]


# ---------------------------------------------------------------------------
# MadGraph point: S5 stealth SUSY / light RPV cascade
# ---------------------------------------------------------------------------

RPV_PROC_CARD = """import model RPVMSSM_UFO

define sq = ur ul cr cl dr dl sr sl
define sq~ = ur~ ul~ cr~ cl~ dr~ dl~ sr~ sl~

generate p p > sq sq~

output _OUTDIR_
"""


def rpv_run_card(nevents_placeholder="_NEVENTS_"):
    """
    Run card with every pT / dR / mass cut zeroed and MLM matching OFF.

    The repo's existing cards ship ickkw = 1 with xqcut = 20 and ptj1min = 10.
    Spec section 4 explicitly forbids MLM here (a low xqcut in this regime is
    unstable), and ptj1min = 10 would bias a signal whose jets are 10-30 GeV.
    Both are therefore overridden, and the conflict is flagged in the point
    README as the spec asks.
    """
    return """#*********************************************************************
# AIDA-Scout S5 run card.  Derived from the repo's standard run card with
# ickkw / xqcut / ptj1min forced off -- see spec section 4.
#*********************************************************************
  RPV       = run_tag ! name of the run
  {nev} = nevents ! Number of unweighted events requested
  _ISEED_   = iseed   ! rnd seed (0=assigned automatically=default))
     1        = lpp1    ! beam 1 type
     1        = lpp2    ! beam 2 type
     7000.0     = ebeam1  ! beam 1 total energy in GeV
     7000.0     = ebeam2  ! beam 2 total energy in GeV
     nn23lo1    = pdlabel     ! PDF set
     230000    = lhaid     ! if pdlabel=lhapdf, this is the lhapdf number
 False = fixed_ren_scale  ! if .true. use fixed ren scale
 False        = fixed_fac_scale  ! if .true. use fixed fac scale
 91.188  = scale            ! fixed ren scale
 91.188  = dsqrt_q2fact1    ! fixed fact scale for pdf1
 91.188  = dsqrt_q2fact2    ! fixed fact scale for pdf2
 -1 = dynamical_scale_choice ! Choose one of the preselected dynamical choices
 1.0  = scalefact        ! scale factor for event-by-event scales
  False     = gridpack  !True = setting up the grid pack
  -1.0 = time_of_flight ! threshold (in mm) below which the invariant livetime is not written
  3.0 = lhe_version       ! Change the way clustering information pass to shower.
  True = clusinfo         ! include clustering tag in output
  average =  event_norm       ! average/sum. Normalization of the weight in the LHEF
 0 = ickkw            ! 0 no matching, 1 MLM   <-- MLM OFF, see spec section 4
 1.0 = alpsfact         ! scale factor for QCD emission vx
 False = chcluster        ! cluster only according to channel diag
 5 = asrwgtflavor     ! highest quark flavor for a_s reweight
 True  = auto_ptj_mjj  ! Automatic setting of ptj and mjj if xqcut >0
 False        = pdfwgt           ! for ickkw=1, perform pdf reweighting
 0.0 = xqcut   ! minimum kt jet measure between partons   <-- no merging scale
   0  = nhel          ! using helicities importance sampling or not.
 None = bias_module  ! Bias type of bias, [None, ptj_bias, -custom_folder-]
 {{}} = bias_parameters ! Specifies the parameters of the module.
  15.0  = bwcutoff      ! (M+/-bwcutoff*Gamma)
   False  = cut_decays    ! Cut decay products
 0.0  = ptj       ! minimum pt for the jets
 0.0  = ptb       ! minimum pt for the b
 0.0  = pta       ! minimum pt for the photons
 0.0  = ptl       ! minimum pt for the charged leptons
 0.0  = misset    ! minimum missing Et (sum of neutrino's momenta)
 -1.0  = ptjmax    ! maximum pt for the jets
 -1.0  = ptbmax    ! maximum pt for the b
 -1.0  = ptamax    ! maximum pt for the photons
 -1.0  = ptlmax    ! maximum pt for the charged leptons
 -1.0  = missetmax ! maximum missing Et (sum of neutrino's momenta)
 {{}} = pt_min_pdg ! pt cut for other particles (use pdg code).
 {{}}	= pt_max_pdg ! pt cut for other particles
  0.0  = ej     ! minimum E for the jets
  0.0  = eb     ! minimum E for the b
  0.0  = ea     ! minimum E for the photons
  0.0  = el     ! minimum E for the charged leptons
  -1.0   = ejmax ! maximum E for the jets
 -1.0   = ebmax ! maximum E for the b
 -1.0   = eamax ! maximum E for the photons
 -1.0   = elmax ! maximum E for the charged leptons
 {{}} = e_min_pdg ! E cut for other particles (use pdg code).
 {{}} = e_max_pdg ! E cut for other particles
  -1.0 = etaj    ! max rap for the jets
  -1.0  = etab    ! max rap for the b
 -1  = etaa    ! max rap for the photons
 -1  = etal    ! max rap for the charged leptons
 0.0  = etajmin ! min rap for the jets
 0.0  = etabmin ! min rap for the b
 0.0  = etaamin ! min rap for the photons
 0.0  = etalmin ! main rap for the charged leptons
 {{}} = eta_min_pdg ! rap cut for other particles (use pdg code).
 {{}} = eta_max_pdg ! rap cut for other particles
 0.0 = drjj    ! min distance between jets
 0.0   = drbb    ! min distance between b's
 0.0 = drll    ! min distance between leptons
 0.0 = draa    ! min distance between gammas
 0.0   = drbj    ! min distance between b and jet
 0.0 = draj    ! min distance between gamma and jet
 0.0 = drjl    ! min distance between jet and lepton
 0.0   = drab    ! min distance between gamma and b
 0.0   = drbl    ! min distance between b and lepton
 0.0 = dral    ! min distance between gamma and lepton
 -1.0  = drjjmax ! max distance between jets
 -1.0  = drbbmax ! max distance between b's
 -1.0  = drllmax ! max distance between leptons
 -1.0  = draamax ! max distance between gammas
 -1.0  = drbjmax ! max distance between b and jet
 -1.0  = drajmax ! max distance between gamma and jet
 -1.0  = drjlmax ! max distance between jet and lepton
 -1.0  = drabmax ! max distance between gamma and b
 -1.0  = drblmax ! max distance between b and lepton
 -1.0  = dralmax ! maxdistance between gamma and lepton
 0.0   = mmjj    ! min invariant mass of a jet pair
 0.0   = mmbb    ! min invariant mass of a b pair
 0.0   = mmaa    ! min invariant mass of gamma gamma pair
 0.0   = mmll    ! min invariant mass of l+l- (same flavour) lepton pair
 -1.0  = mmjjmax ! max invariant mass of a jet pair
 -1.0  = mmbbmax ! max invariant mass of a b pair
 -1.0  = mmaamax ! max invariant mass of gamma gamma pair
 -1.0  = mmllmax ! max invariant mass of l+l- (same flavour) lepton pair
 {{}} = mxx_min_pdg ! min invariant mass of a pair of particles X/X~
 {{'default': False}} = mxx_only_part_antipart !
 0.0   = mmnl    ! min invariant mass for all letpons (l+- and vl)
 -1.0  = mmnlmax ! max invariant mass for all letpons (l+- and vl)
 0.0   = ptllmin  ! Minimum pt for 4-momenta sum of leptons(l and vl)
 -1.0  = ptllmax  ! Maximum pt for 4-momenta sum of leptons(l and vl)
 0.0  = ptheavy   ! minimum pt for at least one heavy final state
 0.0  = xptj ! minimum pt for at least one jet
 0.0  = xptb ! minimum pt for at least one b
 0.0  = xpta ! minimum pt for at least one photon
 0.0  = xptl ! minimum pt for at least one charged lepton
 0.0   = ptj1min ! minimum pt for the leading jet in pt   <-- zeroed
 0.0   = ptj2min ! minimum pt for the second jet in pt
 0.0   = ptj3min ! minimum pt for the third jet in pt
 0.0   = ptj4min ! minimum pt for the fourth jet in pt
 -1.0  = ptj1max ! maximum pt for the leading jet in pt
 -1.0  = ptj2max ! maximum pt for the second jet in pt
 -1.0  = ptj3max ! maximum pt for the third jet in pt
 -1.0  = ptj4max ! maximum pt for the fourth jet in pt
 0   = cutuse  ! reject event if fails any (0) / all (1) jet pt cuts
 0.0   = ptl1min ! minimum pt for the leading lepton in pt
 0.0   = ptl2min ! minimum pt for the second lepton in pt
 0.0   = ptl3min ! minimum pt for the third lepton in pt
 0.0   = ptl4min ! minimum pt for the fourth lepton in pt
 -1.0  = ptl1max ! maximum pt for the leading lepton in pt
 -1.0  = ptl2max ! maximum pt for the second lepton in pt
 -1.0  = ptl3max ! maximum pt for the third lepton in pt
 -1.0  = ptl4max ! maximum pt for the fourth lepton in pt
 0.0   = htjmin ! minimum jet HT=Sum(jet pt)
 -1.0  = htjmax ! maximum jet HT=Sum(jet pt)
 0.0   = ihtmin  !inclusive Ht for all partons (including b)
 -1.0  = ihtmax  !inclusive Ht for all partons (including b)
 0.0   = ht2min ! minimum Ht for the two leading jets
 0.0   = ht3min ! minimum Ht for the three leading jets
 0.0   = ht4min ! minimum Ht for the four leading jets
 -1.0  = ht2max ! maximum Ht for the two leading jets
 -1.0  = ht3max ! maximum Ht for the three leading jets
 -1.0  = ht4max ! maximum Ht for the four leading jets
 0.0 = ptgmin ! Min photon transverse momentum
 0.4 = R0gamma ! Radius of isolation code
 1.0 = xn ! n parameter of eq.(3.4) in hep-ph/9801442
 1.0 = epsgamma ! epsilon_gamma parameter of eq.(3.4) in hep-ph/9801442
 True = isoEM ! isolate photons from EM energy (photons and leptons)
 0.0   = xetamin ! minimum rapidity for two jets in the WBF case
 0.0   = deltaeta ! minimum rapidity for two jets in the WBF case
 -1.0  =  ktdurham
 0.4   =  dparameter
 -1.0  =  ptlund
 1, 2, 3, 4, 5, 6, 21  =  pdgs_for_merging_cut ! PDGs for two cuts above
 5 = maxjetflavor    ! Maximum jet pdg code
   True  = use_syst      ! Enable systematics studies
""".format(nev=nevents_placeholder)


def rpv_customize(m_squark):
    """
    Compressed RPV spectrum with lambda'' UDD decays.

    The squark is the LSP-adjacent state and decays directly through the UDD
    operator to two light jets, so there is no MET and no long cascade of hard
    objects -- the jets are soft simply because the parent is light and the
    decay is 2-body into quarks.  Neutralino and gluino are pushed above the
    squark so squark pair production dominates.
    """
    heavy = m_squark + 200.0
    return """# AIDA-Scout S5: compressed light-squark RPV UDD spectrum.
# Right-handed up/charm/down/strange squarks degenerate at {m:g} GeV; everything
# else decoupled so that p p > sq sq~ dominates and each squark decays via the
# lambda'' UDD operator into two light quarks.
set param_card mass 1000001 {m:g}
set param_card mass 1000002 {m:g}
set param_card mass 1000003 {m:g}
set param_card mass 1000004 {m:g}
set param_card mass 2000001 {m:g}
set param_card mass 2000002 {m:g}
set param_card mass 2000003 {m:g}
set param_card mass 2000004 {m:g}

# Third generation squarks and the gluino out of reach.
set param_card mass 1000005 {heavy:g}
set param_card mass 1000006 {heavy:g}
set param_card mass 2000005 {heavy:g}
set param_card mass 2000006 {heavy:g}
set param_card mass 1000021 {heavy:g}

# Gauginos decoupled ABOVE the squark.  This is essential, not cosmetic: with
# the UFO defaults the neutralino sits near 100 GeV and the squarks decay
# predominantly to q + neutralino/chargino, which produces exactly the MET that
# S5 is supposed not to have (measured before this was set: BR(dl -> b n2) = 1.0,
# BR(ul -> b x1+) = 0.26).  Pushing them above the squark closes those channels
# and leaves only the RPV UDD decay open.
set param_card mass 1000022 {heavy:g}
set param_card mass 1000023 {heavy:g}
set param_card mass 1000024 {heavy:g}
set param_card mass 1000025 {heavy:g}
set param_card mass 1000035 {heavy:g}
set param_card mass 1000037 {heavy:g}

# lambda'' UDD couplings, block RVLAMUDD, indices ijk of lambda''_ijk U_i D_j D_k
# (antisymmetric in the last two).
#
# The UFO ships **0.2 on every entry**, which is not a harmless default: leaving
# it in place opens decays into the third generation, and a 300 GeV squark then
# decays to a top (measured: modes -3 -6 and -5 -6 on the 2000001 squark). S5
# calls for decays to *light* quarks, so every entry is zeroed first and only
# lambda''_112 (u d s -- the sole combination with all indices in the first two
# generations) is switched back on.
set param_card rvlamudd 1 1 3 0.0
set param_card rvlamudd 1 2 3 0.0
set param_card rvlamudd 1 3 1 0.0
set param_card rvlamudd 1 3 2 0.0
set param_card rvlamudd 2 1 2 0.0
set param_card rvlamudd 2 1 3 0.0
set param_card rvlamudd 2 2 1 0.0
set param_card rvlamudd 2 2 3 0.0
set param_card rvlamudd 2 3 1 0.0
set param_card rvlamudd 2 3 2 0.0
set param_card rvlamudd 3 1 2 0.0
set param_card rvlamudd 3 1 3 0.0
set param_card rvlamudd 3 2 1 0.0
set param_card rvlamudd 3 2 3 0.0
set param_card rvlamudd 3 3 1 0.0
set param_card rvlamudd 3 3 2 0.0

# The only surviving coupling: u d s.  1e-2 keeps the decay prompt on detector
# scales while leaving the squark narrow.
set param_card rvlamudd 1 1 2 1.0e-2
set param_card rvlamudd 1 2 1 -1.0e-2

# Recompute the squark widths so the RPV UDD channel is present in the decay
# table that gets written into the LHE header and handed to Pythia.  Without
# this the squarks inherit the UFO's default table and may not decay to
# two quarks at all.
compute_widths 1000001 1000002 1000003 1000004 2000001 2000002 2000003 2000004
""".format(m=m_squark, heavy=heavy)


def rpv_points():
    out = []
    for m in (300, 600):
        name = "RPV_squark{0}_UDD".format(m)
        out.append((name, float(m)))
    return out


# ---------------------------------------------------------------------------
# Per-point READMEs (spec deliverable 5.6)
# ---------------------------------------------------------------------------

MENU = """
| Seed | Threshold | Fires? |
|---|---|---|
| PuppiHT | 450 (constituents pT > 30) | {ht} |
| SinglePuppiJet | 230 | {jet} |
| QuadJet | 400,70,55,40,40 | {quad} |
| DoubleTkMuon (BPH) | 2,2, abs(eta)<1.5, dR<1.4, OS, dz<1cm | {bph} |
| DoubleTkMuon (central) | 4,4 | {mu44} |
| DoubleTkElectron | 25,12 | {ele} |
| DoubleTkIsoPhoton | 22,12 | {pho} |
| DoublePuppiTau | 52,52 | {tau} |
| PuppiETmiss | 200 | {met} |
"""

README_HEAD = """# {name}

**AIDA-Scout {sid}** -- generated by `make_signal_cards.py`.

{what}

## Configuration

{config}

## Why it evades (or does not evade) the Phase-2 L1 menu
{menu}
{notes}
## Running

```bash
apptainer exec --bind $simdir \\
  /cvmfs/unpacked.cern.ch/registry.hub.docker.com/jmduarte/mapyde:latest \\
  sh $simdir/run.sh {name} <nevents> <seed> $simdir False
```

This point uses the **{mode}** branch of `run.sh`.
"""


def write_readme(path, **kw):
    kw.setdefault("notes", "")
    with open(path, "w") as fh:
        fh.write(README_HEAD.format(**kw))


HV_CAVEATS = """
## Caveats specific to this chain

* **No external Hidden Valley UFO is used.** The hard process is Pythia's own
  `HiddenValley:ffbar2Zv`, so the 4900xxx identity conventions of the hard
  process and of the shower are guaranteed to agree. This resolves open item 3
  of the specification: there is no UFO/module mismatch to check.
* **`nFlav = 2` leaves roughly half the dark shower invisible.** The
  off-diagonal dark mesons `4900211` / `4900213` carry a conserved dark flavour
  and have empty decay tables; they are marked stable explicitly. Measured on a
  50-event test at m_Zp = 500 / m_piD = 2: 5.4 decaying vs 5.2 stable dark
  mesons per event. This is identical between the ee and mumu samples, so the
  controlled comparison is unaffected.
* **The vectors are forced too.** With `probVector = 0.75` three quarters of the
  dark mesons are `rhov`. The specification fragment pins only `4900111`, which
  would have left most of the visible energy on the default flavour-democratic
  table and destroyed the ee/mumu contrast. `4900113` and `4900223` are
  therefore forced to the same channel. **This is an extension of the
  specification fragment, flagged here as requested.**
* **No MLM matching**, per specification section 4. The hard process is the
  resonance only; the shower supplies all extra radiation.
"""


def s2_readme_body(mzp, mpi, flav):
    other = "ee" if flav == "mumu" else "mumu"
    if flav == "mumu":
        verdict = ("**This is the *covered* member of the pair.** The BPH "
                   "DoubleTkMuon 2,2 seed should fire in most events, which is "
                   "the point: it is the calibration/reference sample (C2 when "
                   "ctau = 0) against which the ee sample is compared.")
        bph, ele = "**YES** (by design)", "no muons -> N/A"
    else:
        verdict = ("**This is the *uncovered* member of the pair.** There is no "
                   "di-electron seed below 12 GeV, so the identical kinematics "
                   "that the mumu sample hands to the BPH seed have no "
                   "electron equivalent to catch them.")
        bph, ele = "no muons -> N/A", "**no** (leptons far below 25,12)"
    return verdict, bph, ele


def build_readmes(outdir):
    # ---- S2 ----
    for mzp in (500, 1000):
        for mpi in (2, 5):
            for flav in ("ee", "mumu"):
                name = "HVdilep_Zp{0}_piD{1}_{2}".format(mzp, mpi, flav)
                verdict, bph, ele = s2_readme_body(mzp, mpi, flav)
                lep = "e+e-" if flav == "ee" else "mu+mu-"
                write_readme(
                    os.path.join(outdir, name, "README.md"),
                    name=name, sid="S2 (dark shower to soft dileptons)",
                    mode="pythia",
                    what=("A Hidden Valley Z' of {0} GeV decays to a pair of dark quarks, "
                          "which shower and hadronise in the hidden sector into dark mesons "
                          "of mass {1} GeV (vectors at {2} GeV). Every decaying dark meson "
                          "is forced to **{3}**, giving a handful of soft, collimated "
                          "leptons of a single flavour.\n\n"
                          "This point is one half of the matched ee/mumu pair: its partner is "
                          "`HVdilep_Zp{0}_piD{1}_{4}`, which is **identical in every respect "
                          "except the lepton flavour**.").format(mzp, mpi, 2 * mpi, lep, other_flav(flav)),
                    config=("* Hard process: `HiddenValley:ffbar2Zv`, m_Zp = {0} GeV\n"
                            "* Lambda = {1} GeV, pTminFSR = {2:g} GeV, Ngauge = 3, nFlav = 2, probVector = 0.75\n"
                            "* m_piD = {1} GeV, m_rhoD = {3} GeV, m_qv = {1} GeV\n"
                            "* Dark meson decays: 100% -> {4}\n"
                            "* Cross section: **{5} pb** (Pythia LO, no k-factor)\n"
                            "* Expected multiplicity: ~11 leptons/event at the "
                            "Zp500/piD2 point (measured)").format(
                                mzp, mpi, 1.1 * mpi, 2 * mpi, lep, S2_XSEC[(mzp, mpi, flav)]),
                    menu=MENU.format(
                        ht="see caveat below", jet="see caveat below", quad="no",
                        bph=bph, mu44="**YES** if mumu" if flav == "mumu" else "N/A",
                        ele=ele, pho="no", tau="no", met="no"),
                    notes=HV_CAVEATS + S2_HADRONIC_WARNING)

    # ---- S3 ----
    for ctau in (1, 10, 100):
        name = "HVdilep_Zp500_piD2_mumu_ctau{0}mm".format(ctau)
        write_readme(
            os.path.join(outdir, name, "README.md"),
            name=name, sid="S3 (displaced soft dimuons)", mode="pythia",
            what=("Identical to `HVdilep_Zp500_piD2_mumu` except that every decaying "
                  "dark meson is given a proper lifetime of **ctau = {0} mm**. The "
                  "ctau = 0 reference point is `HVdilep_Zp500_piD2_mumu` itself, which "
                  "doubles as control C2.").format(ctau),
            config=("* As `HVdilep_Zp500_piD2_mumu`\n"
                    "* `4900111/4900221/4900113/4900223:tau0 = {0}` mm\n"
                    "* `ParticleDecays:limitTau0 = off` -- **required**; the default "
                    "CMS-style `tau0Max = 10 mm` would stop the dark mesons decaying "
                    "at all and make the sample silently invisible\n"
                    "* Cross section: **5.585 pb** (unchanged by the lifetime)").format(ctau),
            menu=MENU.format(ht="no", jet="no", quad="no",
                             bph="**intended: no** -- but see the blocker below",
                             mu44="**intended: no**", ele="N/A", pho="no",
                             tau="no", met="no"),
            notes=S3_BLOCKER.format(ctau=ctau) + HV_CAVEATS)

    # ---- S1 / C1 ----
    for m_phi, lam in ((125, 1.0), (125, 2.0), (400, 2.0), (400, 4.0)):
        name = "SUEPlike_HV_mPhi{0}_mX2_Lam{1:g}".format(m_phi, lam)
        write_readme(
            os.path.join(outdir, name, "README.md"),
            name=name, sid="S1 (SUEP) -- APPROXIMATION, see warning", mode="pythia",
            what=("A {0} GeV scalar is produced through gluon fusion and decays through a "
                  "Higgs portal into the hidden sector, which showers into many soft dark "
                  "mesons of mass 2 GeV that decay back to light SM quarks. The result is a "
                  "soft, high-multiplicity, all-hadronic event with no MET and no hard "
                  "jet.\n\n"
                  "Generated with **no ISR requirement**, per specification section S1 "
                  "'Critical'. The ISR-tagged version is the separate control point "
                  "`SUEPlike_HV_mPhi125_mX2_Lam2_ISR` (C1).").format(m_phi),
            config=("* Hard process: `HiggsSM:gg2H`, m_phi = {0} GeV\n"
                    "* Portal: `25:addChannel ... 4900101 -4900101`, all SM decays closed\n"
                    "* Lambda = {1:g} GeV, pTminFSR = {2:g} GeV, m_X = 2 GeV, m_rhoD = 4 GeV\n"
                    "* Dark mesons -> light quarks (s sbar for the pseudoscalars, u/d/s for "
                    "the vectors); the default table is b-dominated and inaccessible at 2 GeV\n"
                    "* Reference cross section sigma(gg -> phi) = **{3} pb** "
                    "(Pythia LO, no k-factor)\n"
                    "* **Normalisation warning:** the sigma printed by the generator is "
                    "sigma(gg->phi) multiplied by Pythia's internal open-channel fraction. "
                    "For an *added* exotic channel that fraction is a width-bookkeeping "
                    "artifact, not a physical branching ratio (it comes out ~1.4e-4 at "
                    "m_phi = 400). **Normalise as sigma(gg->phi) x BR(phi->hidden) using "
                    "the reference sigma above and your own assumed BR.**").format(
                        m_phi, lam, 1.1 * lam, GGH_XSEC[m_phi]),
            menu=MENU.format(ht="no (energy spread over many soft hadrons)",
                             jet="no", quad="no", bph="no", mu44="no", ele="no",
                             pho="no", tau="no", met="no (fully visible decay)"),
            notes=SUEP_WARNING)

    name = "SUEPlike_HV_mPhi125_mX2_Lam2_ISR"
    write_readme(
        os.path.join(outdir, name, "README.md"),
        name=name, sid="C1 (control: boosted SUEP-like with hard ISR)", mode="pythia",
        what=("The same model as `SUEPlike_HV_mPhi125_mX2_Lam2`, but produced in "
              "association with a hard recoil jet (`pTHatMin = 150` GeV). This is the "
              "negative control: it **should** be caught by the existing hadronic seeds, "
              "and if the anomaly detector flags it that must not be part of the headline "
              "sensitivity claim."),
        config=("* Hard process: `HiggsSM:gg2Hg(l:t)`, `qg2Hq(l:t)`, `qqbar2Hg(l:t)` with "
                "`PhaseSpace:pTHatMin = 150`\n"
                "* Hidden sector identical to `SUEPlike_HV_mPhi125_mX2_Lam2`\n"
                "* Reference cross section sigma(gg->phi+j, pTHat>150) = **1.945 pb** "
                "(Pythia LO); same normalisation warning as the nominal point"),
        menu=MENU.format(ht="**likely YES**", jet="**likely YES** (recoil jet ~150-250 GeV)",
                         quad="no", bph="no", mu44="no", ele="no", pho="no",
                         tau="no", met="no"),
        notes=SUEP_WARNING + C4_NOTE)

    # ---- S4 ----
    for ma in (5, 10, 15):
        name = "hToAA_4tau_ma{0}".format(ma)
        write_readme(
            os.path.join(outdir, name, "README.md"),
            name=name, sid="S4 (multi-soft-tau)", mode="pythia",
            what=("A 125 GeV Higgs produced by gluon fusion decays to a pair of light "
                  "pseudoscalars of mass {0} GeV, each of which decays to tau+ tau-. "
                  "The final state is four taus sharing 125 GeV, so each tau carries "
                  "roughly 30 GeV and each tau *jet* considerably less.").format(ma),
            config=("* Hard process: `HiggsSM:gg2H`, m_h = 125 GeV\n"
                    "* `25:addChannel -> 36 36`, all SM Higgs decays closed\n"
                    "* m_a = {0} GeV, `36:addChannel -> 15 -15`, prompt (`tau0 = 0`)\n"
                    "* No 2HDM+S UFO is required -- this is entirely a decay-table "
                    "configuration, which is why it runs on the pythia branch\n"
                    "* Reference cross section sigma(gg->h) = **28.07 pb** (Pythia LO, "
                    "no k-factor); same normalisation warning as S1 -- rescale by your "
                    "assumed BR(h->aa)").format(ma),
            menu=MENU.format(ht="no", jet="no", quad="no", bph="no", mu44="no",
                             ele="no", pho="no",
                             tau="**no** -- the 52,52 PuppiTau floor is far above a "
                                 "tau from a 125/4 GeV share",
                             met="no (neutrinos partly cancel)"),
            notes=("\n## Note\n\nThe leptonic tau decays give a few soft electrons and "
                   "muons. The muonic ones can occasionally reach the BPH DoubleTkMuon "
                   "2,2 seed, so this point is not a *pure* trigger-blind sample; "
                   "quantify the leakage before using it in a sensitivity claim.\n"))

    # ---- C3 ----
    write_readme(
        os.path.join(outdir, "Zprime_qq_m500", "README.md"),
        name="Zprime_qq_m500", sid="C3 (control: low-mass dijet resonance)",
        mode="pythia",
        what=("A 500 GeV sequential Z' decaying to light quarks, giving two jets of "
              "roughly 250 GeV each. This is the standard 'the anomaly detector should "
              "not claim credit here' control: the event is comfortably inside the "
              "existing menu."),
        config=("* Hard process: `NewGaugeBoson:ffbar2gmZZprime` with `Zprime:gmZmode = 3` "
                "(pure Z', no gamma/Z interference)\n"
                "* m_Z' = 500 GeV, decays forced to u/d/s/c/b\n"
                "* Cross section: **154.8 pb** (Pythia LO, no k-factor). This is the "
                "full sequential-Z' coupling strength and is deliberately unphysical as a "
                "signal rate -- it is a control, only the shape matters."),
        menu=MENU.format(ht="**YES** (HT ~ 500)", jet="**YES** (~250 GeV jets)",
                         quad="no", bph="no", mu44="no", ele="no", pho="no",
                         tau="no", met="no"),
        notes="")

    # ---- S5 ----
    for m in (300, 600):
        name = "RPV_squark{0}_UDD".format(m)
        write_readme(
            os.path.join(outdir, name, "README.md"),
            name=name, sid="S5 (stealth SUSY / light RPV cascade)", mode="madgraph",
            what=("Pair production of degenerate light squarks at {0} GeV, each decaying "
                  "through the R-parity-violating lambda'' UDD operator directly into two "
                  "light quarks. The result is a high-multiplicity all-hadronic event with "
                  "**no MET** -- a different menu failure mode from S1: high multiplicity "
                  "but *not* isotropic.").format(m),
            config=("* Model: `RPVMSSM_UFO` (already present in the container's MG5 "
                    "installation -- no download needed)\n"
                    "* `generate p p > sq sq~` over the eight light-flavour squarks\n"
                    "* m_squark = {0} GeV, gluino/gauginos/3rd generation decoupled at "
                    "{1} GeV so squark pair production dominates and no MET is produced\n"
                    "* lambda'' UDD couplings 1e-2 (prompt, but narrow)\n"
                    "* **run_card deviates from the repo convention:** `ickkw = 0`, "
                    "`xqcut = 0`, `ptj1min = 0`. The repo's standard cards ship "
                    "`ickkw = 1 / xqcut = 20 / ptj1min = 10`; specification section 4 "
                    "forbids MLM here and a 10 GeV leading-jet cut would bias a signal "
                    "whose jets are 10-30 GeV. **Conflict flagged rather than silently "
                    "followed, as requested.**\n"
                    "* Cross section: taken from the MG5 run output (`run_01` banner)").format(
                        m, m + 200),
            menu=MENU.format(ht="**borderline** -- verify per point; target is HT < 450",
                             jet="no (target 10-30 GeV jets)", quad="**possibly** -- verify",
                             bph="no", mu44="no", ele="no", pho="no", tau="no",
                             met="no (RPV: no LSP escapes)"),
            notes=("\n## Validation status\n\n"
                   "**Partially validated. Do not use without the checks below.**\n\n"
                   "What was confirmed on a 200-event test at m_squark = 300 GeV:\n\n"
                   "* The `RPVMSSM_UFO` process builds (76 subprocesses) and integrates; "
                   "sigma(p p > sq sq~) = **70.67 +- 0.13 pb** at m_squark = 300 GeV.\n"
                   "* `set param_card mass ...` is accepted for the squarks (the mass "
                   "block is an input in this UFO).\n"
                   "* `compute_widths` does populate the RPV UDD channels: the squark "
                   "decay table contains the two-quark modes `-3 -1`, `-5 -1`, `-5 -3`.\n\n"
                   "What was found and fixed: with the UFO's default spectrum the "
                   "neutralino sits near 100 GeV and the squarks decay mostly to "
                   "q + neutralino/chargino -- `BR(dl -> b n2) = 1.0` and "
                   "`BR(ul -> b x1+) = 0.26` were measured. That is exactly the MET S5 is "
                   "supposed not to have. The customizecards now decouple all gauginos "
                   "above the squark to close those channels.\n\n"
                   "A second round of testing after the gaugino fix confirmed the squarks "
                   "then decay **100% to two quarks with no neutralino/chargino channels** "
                   "(sigma = 70.23 +- 0.12 pb), but exposed two further problems, now "
                   "addressed in the customizecards and **not yet re-tested**:\n\n"
                   "* The UFO ships lambda'' = 0.2 on *every* RVLAMUDD entry. That opened "
                   "third-generation modes, and a 300 GeV squark was decaying to a **top "
                   "quark** (`-3 -6`, `-5 -6`). All entries are now zeroed except "
                   "lambda''_112.\n"
                   "* With the gauginos decoupled, squarks that carry no UDD coupling have "
                   "**no open channel at all**: `DECAY 1000001` came back with width "
                   "exactly 0, i.e. a stable coloured particle. With only lambda''_112 on, "
                   "only three squark flavours have an open decay.\n\n"
                   "**Still to check before production:**\n\n"
                   "1. Re-read the decay table and confirm no squark in the `sq` "
                   "definition has zero width. If any still do, narrow the `define sq` "
                   "line in the proc_card to only the flavours lambda''_112 actually "
                   "couples to -- otherwise the sample contains stable coloured particles "
                   "and is unusable.\n"
                   "2. Confirm MET is genuinely small at reco level.\n"
                   "3. The jet spectrum is the real physics question: a two-body decay at "
                   "m_squark = {0} GeV gives jets of roughly m/2 = {1} GeV, which is "
                   "**above** the 10-30 GeV target in the specification and may reach the "
                   "HT 450 seed. This point currently produces 4 hard jets, not the "
                   "'8-12 jets of 10-30 GeV' that S5 asks for. Getting there needs an "
                   "intermediate near-degenerate state in the cascade so the visible "
                   "energy is shared among more, softer jets -- i.e. a genuinely "
                   "compressed spectrum rather than the direct 2-body decay used "
                   "here.\n").format(m, m // 2))


def other_flav(f):
    return "ee" if f == "mumu" else "mumu"


S2_HADRONIC_WARNING = """
## Measured behaviour (50-event test, PU 200, m_Zp = 500 / m_piD = 2, mumu)

Reconstructed with the repo's Delphes L1T view:

* L1T PUPPI candidates: **~6700 per event**
* Leading L1T PUPPI jet pT: median **123 GeV**, 90th percentile **213 GeV**, max **241 GeV**
* HT over PUPPI jets above 30 GeV: median **195 GeV**, 90th percentile **377 GeV**, max **470 GeV**
* L1T muons: **4.7 per event**, median pT 20.7 GeV; **78% of events have two muons
  above 2 GeV within abs(eta) < 1.5**

Measured seed fire rates (50 events each, PU 200):

| Seed | ee | mumu |
|---|---|---|
| PuppiHT 450 | 0.04 | 0.04 |
| SinglePuppiJet 230 | 0.04 | 0.02 |
| DoubleTkMuon 2,2 | 0.00 | **0.78** |
| DoubleTkMuon 4,4 | 0.00 | **0.90** |
| DoubleTkElectron 25,12 | **0.58** | 0.00 |
| PuppiETmiss 200 | 0.06 | 0.04 |

## THE ee SAMPLE IS NOT UNCOVERED AT THIS BENCHMARK POINT

`DoubleTkElectron 25,12` fires in **58%** of ee events. The premise of S2 is that
soft di-electrons have no seed below 12 GeV, but at m_Zp = 500 GeV the electrons
are not soft: median reconstructed pT is 27.8 GeV, far above the floor. **As
configured, this point does not demonstrate the gap it was designed to
demonstrate.**

Root cause: the dark meson multiplicity is too low. Only ~5-6 decaying dark
mesons share the whole event, so each carries ~50 GeV and its two leptons ~25 GeV
each.

**Lambda is not the lever.** A scan over Lambda = 0.5, 1, 2 GeV changes the dark
meson multiplicity by less than 10% (4.0 -> 5.8 mesons/event). The reason is the
specification's own `pTminFSR = 1.1 x Lambda` rule: it ties the shower cutoff to
Lambda, so lowering Lambda lowers the cutoff by the same factor and the amount of
hidden-sector radiation barely moves.

**`HiddenValley:alphaFSR` is the lever.** Decoupling the cutoff from Lambda
(`alphaOrder = 0`, fixed `alphaFSR`, `pTminFSR = 0.5`) at m_Zp = 500 GeV gives:

| alphaFSR | dark mesons | leptons | median lepton pT | DoubleTkEle 25,12 |
|---|---|---|---|---|
| (nominal, alphaOrder=1) | 5.8 | 10.9 | 5.0 GeV | 0.73 |
| 0.5 | 11.3 | 20.8 | 4.0 GeV | 0.69 |
| 0.8 | 14.3 | 25.9 | 3.4 GeV | 0.59 |
| 1.2 | 17.4 | 31.1 | 3.1 GeV | **0.49** |

Even at alphaFSR = 1.2 the fire rate is only halved, because the hard tail
survives. Lowering m_Zp is the complementary lever: at m_Zp = 200 GeV the
nominal configuration already drops to 0.36.

**Recommendation, for a decision rather than a silent change:** the cards as
shipped follow the specification (`alphaOrder = 1`, `pTminFSR = 1.1 x Lambda`,
m_Zp = 500/1000). To make the ee sample genuinely uncovered, they need
`alphaOrder = 0` with `alphaFSR` around 1 **and** a lower m_Zp (200-300 GeV).
That is a change to the specification's benchmark points, so it was not applied
unilaterally.

**Second caveat.** Because every dark meson decays to a lepton pair, the leptons
themselves cluster into PUPPI jets. At m_Zp = 500 GeV this produces ~120 GeV jets
and an HT tail reaching 470 GeV. The hadronic seeds fire at only ~4%, so this is
not currently the dominant problem, but it should be re-checked at any new
parameter point.
"""

SUEP_WARNING = """
## WARNING -- THIS IS NOT A SUEP SAMPLE

This point uses Pythia's **Hidden Valley** module as a stand-in for a SUEP
generator. It was generated this way as a deliberate, time-boxed choice; the
difference is physical, not cosmetic:

* A real SUEP is a **thermal** shower: dark hadrons are drawn from a Boltzmann
  distribution at temperature T and emitted **isotropically** in the mediator
  rest frame. That isotropy is the entire signature, and it is what makes
  structural gap 1 ("isotropic hadronic energy is untriggerable") apply.
* A Hidden Valley shower is **QCD-like**: it produces two back-to-back dark
  jets. The events are soft and high-multiplicity, but they are **not
  isotropic**.

Consequences:

* The `Lambda` parameter here is a stand-in for the dark temperature `T`. The
  mapping is **not** physical -- do not quote it as a temperature.
* The 1.6% leading-jet estimate in specification section 3 (gap 1) assumes
  uniform energy distribution and **does not apply to these events**. Expect
  more energy in the leading jet than a true SUEP would give.
* **Control C4 (anisotropy control) is degenerate with the nominal point under
  this approximation** and cannot be built from it. C4 requires a genuine
  isotropy knob, i.e. a real thermal shower. It is the control the
  specification flags as "most likely to change how we interpret results", so
  this is a real gap in the deliverable.

To do this properly, integrate the Knapen/Griso/Papucci thermal shower (or the
CMS-adopted equivalent) as a Pythia8 UserHook in `main_signal.cc`; the
standalone-main structure added for this campaign is the right place for it.
"""

C4_NOTE = """
## Relationship to C4

Under the Hidden Valley approximation this ISR-tagged point and the intended
anisotropy control C4 collapse into the same sample: both amount to "the same
hidden-sector event, boosted". A genuine C4 needs a thermal shower whose
isotropy can be broken independently of the production kinematics.
"""

S3_BLOCKER = """
## Blocker -- read before using this sample

Specification open item 2 asks whether the simulation chain propagates displaced
decay vertices through to the PUPPI candidates. The answer for this repo is
**partially, and not in the way this signal needs**:

* Delphes' `ParticlePropagator` does start each particle from its true
  production vertex and does compute D0/DZ, so the sample is **correct at truth
  level** and the displacement is really there.
* But the L1T reconstruction in `cards/delphes_card.dat` has **no displacement
  dependence at all**. `L1TChargedHadronTrackingEfficiency`,
  `L1TElectronTrackingEfficiency` and `L1TMuonTrackingEfficiency` are functions
  of `pt` and `eta` only -- there is no |d0| acceptance term anywhere in the
  card.
* The evasion mechanism for S3 is precisely that L1 tracking is prompt and loses
  displaced tracks. **This chain will not reproduce that**, so the sample will
  look approximately as triggerable as the ctau = 0 point rather than
  progressively less so.

Using this sample to claim "displacement defeats tkMuon" therefore requires
either an added d0-dependent efficiency term in the L1T tracking modules, or a
real CMSSW Phase-2 L1 emulation.

A second, smaller effect at long lifetime: Delphes drops particles produced
outside the tracker volume (R = 1.29 m, half-length 3.0 m). At ctau = {ctau} mm
with the boosts in this sample a fraction of the dark mesons decay beyond that
radius, and their muons are discarded entirely rather than being reconstructed
in the muon system.
"""

# Reference cross sections measured with 5-20 event Pythia runs (LO, no k-factor).
S2_XSEC = {
    (500, 2, "ee"): "5.236", (500, 2, "mumu"): "5.585",
    (500, 5, "ee"): "5.237", (500, 5, "mumu"): "4.215",
    (1000, 2, "ee"): "0.4168", (1000, 2, "mumu"): "0.3397",
    (1000, 5, "ee"): "0.4735", (1000, 5, "mumu"): "0.3879",
}
GGH_XSEC = {125: "28.07", 400: "5.212"}


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default="processes")
    args = ap.parse_args()

    written = []

    for name, body in (s2_points() + s3_points() + s1_points()
                       + s4_points() + c3_points()):
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        path = os.path.join(d, "{0}_pythia_card.dat".format(name))
        with open(path, "w") as fh:
            fh.write(body)
        written.append(path)

    for name, m in rpv_points():
        d = os.path.join(args.outdir, name)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "{0}_proc_card.dat".format(name)), "w") as fh:
            fh.write(RPV_PROC_CARD)
        with open(os.path.join(d, "{0}_run_card.dat".format(name)), "w") as fh:
            fh.write(rpv_run_card())
        with open(os.path.join(d, "{0}_customizecards.dat".format(name)), "w") as fh:
            fh.write(rpv_customize(m))
        written.append(d)

    build_readmes(args.outdir)

    print("wrote {0} process definitions".format(len(written)))
    for w in written:
        print("  " + w)


if __name__ == "__main__":
    main()
