ScalarHT/ScalarHT.HT:
    discrete: False
    x_label: '$H_T$ (GeV)'
    save_name: HT.png
Jet:
    discrete: True
    x_label: Number of AK4 jets
    save_name: Jet.png
JetPUPPI:
    discrete: True
    x_label: Number of PUPPI jets
    save_name: PUPPIJet.png