ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MH,MDL_MTA,MDL_MZ,MDL_MW,MDL_MB,MDL_MT

      COMMON/MASSES/ MDL_MH,MDL_MTA,MDL_MZ,MDL_MW,MDL_MB,MDL_MT


      DOUBLE PRECISION MDL_WH,MDL_WW,MDL_WZ,MDL_WT

      COMMON/WIDTHS/ MDL_WH,MDL_WW,MDL_WZ,MDL_WT


      DOUBLE COMPLEX GC_10, GC_11, GC_12

      COMMON/COUPLINGS/ GC_10, GC_11, GC_12

